export type Volatility = "Low" | "Medium" | "High" | "Very High";

export interface SlotGame {
  name: string;
  provider: string;
  image: string;
  volatility: Volatility;
}

// Pragmatic Play CDN base
const PP = (code: string) =>
  `https://pp-slot-cdn.pragmaticplay.net/game-icons/gs2c/square/${code}.png`;

export const SLOT_GAMES: SlotGame[] = [
  // ─── Pragmatic Play ───────────────────────────────────────────────────────
  { name: "Sweet Bonanza", provider: "Pragmatic Play", image: PP("vs20sugarhits"), volatility: "High" },
  { name: "Gates of Olympus", provider: "Pragmatic Play", image: PP("vs20olympgate"), volatility: "High" },
  { name: "Big Bass Bonanza", provider: "Pragmatic Play", image: PP("vs10bigbass"), volatility: "High" },
  { name: "Dog House Megaways", provider: "Pragmatic Play", image: PP("vswaysdogs"), volatility: "High" },
  { name: "The Dog House", provider: "Pragmatic Play", image: PP("vs20doghouse"), volatility: "High" },
  { name: "Starlight Princess", provider: "Pragmatic Play", image: PP("vs20starlight"), volatility: "High" },
  { name: "Wolf Gold", provider: "Pragmatic Play", image: PP("vs25wolfgold"), volatility: "Medium" },
  { name: "Wild West Gold", provider: "Pragmatic Play", image: PP("vs40wildwest"), volatility: "High" },
  { name: "Fruit Party", provider: "Pragmatic Play", image: PP("vs20fruitparty"), volatility: "High" },
  { name: "Chilli Heat", provider: "Pragmatic Play", image: PP("vs25chilliheat"), volatility: "Medium" },
  { name: "Aztec Gems", provider: "Pragmatic Play", image: PP("vs5aztecgems"), volatility: "Low" },
  { name: "Gems Bonanza", provider: "Pragmatic Play", image: PP("vswaysgem"), volatility: "High" },
  { name: "Release the Kraken", provider: "Pragmatic Play", image: PP("vs20kraken"), volatility: "High" },
  { name: "Mustang Gold", provider: "Pragmatic Play", image: PP("vs25mustang"), volatility: "Medium" },
  { name: "Juicy Fruits", provider: "Pragmatic Play", image: PP("vs20juicyfr"), volatility: "High" },
  { name: "Floating Dragon", provider: "Pragmatic Play", image: PP("vs20floatdrg"), volatility: "High" },
  { name: "Hot to Burn", provider: "Pragmatic Play", image: PP("vs20hotburn"), volatility: "Medium" },
  { name: "Peking Luck", provider: "Pragmatic Play", image: PP("vs20pekinglu"), volatility: "Medium" },
  { name: "5 Lions Gold", provider: "Pragmatic Play", image: PP("vs50lionsgold"), volatility: "High" },
  { name: "Lucky Lightning", provider: "Pragmatic Play", image: PP("vs20luckyligh"), volatility: "High" },
  { name: "Money Mouse", provider: "Pragmatic Play", image: PP("vs25moneymouse"), volatility: "Medium" },
  { name: "Magic Journey", provider: "Pragmatic Play", image: PP("vs25magicjourn"), volatility: "Medium" },
  { name: "Leprechaun Song", provider: "Pragmatic Play", image: PP("vs20leprecoins"), volatility: "High" },
  { name: "Da Vinci's Treasure", provider: "Pragmatic Play", image: PP("vs25davinci"), volatility: "Medium" },
  { name: "3 Kingdoms", provider: "Pragmatic Play", image: PP("vs25kingdoms"), volatility: "High" },
  { name: "Great Rhino Megaways", provider: "Pragmatic Play", image: PP("vswaysrhino"), volatility: "High" },
  { name: "Power of Thor Megaways", provider: "Pragmatic Play", image: PP("vswaysftropics"), volatility: "High" },
  { name: "Jokers Jewels", provider: "Pragmatic Play", image: PP("vs5joker"), volatility: "Low" },
  { name: "Buffalo King Megaways", provider: "Pragmatic Play", image: PP("vswaysbufking"), volatility: "High" },
  { name: "Pirate Gold Deluxe", provider: "Pragmatic Play", image: PP("vs40pirate"), volatility: "High" },
  { name: "Book of Fallen", provider: "Pragmatic Play", image: PP("vs10bookoftut"), volatility: "High" },
  { name: "Barn Festival", provider: "Pragmatic Play", image: PP("vs20barnfest"), volatility: "High" },
  { name: "Eye of Cleopatra", provider: "Pragmatic Play", image: PP("vs20eyeofcleo"), volatility: "High" },
  { name: "Fire Strike", provider: "Pragmatic Play", image: PP("vs1firestrike"), volatility: "High" },
  { name: "Curse of the Werewolf Megaways", provider: "Pragmatic Play", image: PP("vswayswwriches"), volatility: "Very High" },
  { name: "Cash Elevator", provider: "Pragmatic Play", image: PP("vs20cashelev"), volatility: "High" },
  { name: "Christmas Carol Megaways", provider: "Pragmatic Play", image: PP("vswayschristmas"), volatility: "High" },
  { name: "Drill That Gold", provider: "Pragmatic Play", image: PP("vs20drillgold"), volatility: "High" },
  { name: "Big Bass Splash", provider: "Pragmatic Play", image: PP("vs10txbigbass"), volatility: "High" },
  { name: "Rainbow Gold", provider: "Pragmatic Play", image: PP("vs5rainbowgold"), volatility: "Medium" },
  { name: "Sweet Bonanza 1000", provider: "Pragmatic Play", image: PP("vs20sugarhits1000"), volatility: "Very High" },
  { name: "Gates of Olympus 1000", provider: "Pragmatic Play", image: PP("vs20olympgate1000"), volatility: "Very High" },
  { name: "Starlight Princess 1000", provider: "Pragmatic Play", image: PP("vs20starlight1000"), volatility: "Very High" },
  { name: "Sugar Rush", provider: "Pragmatic Play", image: PP("vs20sugarrush"), volatility: "High" },
  { name: "Sugar Rush 1000", provider: "Pragmatic Play", image: PP("vs20sugarrush1000"), volatility: "Very High" },
  { name: "Fruit Party 2", provider: "Pragmatic Play", image: PP("vs20fruitparty2"), volatility: "High" },
  { name: "Bigger Bass Bonanza", provider: "Pragmatic Play", image: PP("vs10bigbass2"), volatility: "High" },
  { name: "Big Bass Bonanza Megaways", provider: "Pragmatic Play", image: PP("vswaysbigbass"), volatility: "High" },
  { name: "Big Bass Vegas", provider: "Pragmatic Play", image: PP("vs10bigbassvegas"), volatility: "High" },
  { name: "Big Bass Hold & Spinner Megaways", provider: "Pragmatic Play", image: PP("vs10bbbonanza3"), volatility: "High" },
  { name: "Big Bass Day at the Races", provider: "Pragmatic Play", image: PP("vs10bbdayraces"), volatility: "High" },
  { name: "Big Bass Christmas Bash", provider: "Pragmatic Play", image: PP("vs10christmasbass"), volatility: "High" },
  { name: "Christmas Big Bass Bonanza", provider: "Pragmatic Play", image: PP("vs20xmasbass"), volatility: "High" },
  { name: "The Hand of Midas", provider: "Pragmatic Play", image: PP("vs20midas"), volatility: "Very High" },
  { name: "Rise of Giza PowerNudge", provider: "Pragmatic Play", image: PP("vs20riseofgiza"), volatility: "High" },
  { name: "Goblin Heist Powernudge", provider: "Pragmatic Play", image: PP("vs20gobnudge"), volatility: "High" },
  { name: "5 Lions", provider: "Pragmatic Play", image: PP("vs10lions"), volatility: "High" },
  { name: "5 Lions Megaways", provider: "Pragmatic Play", image: PP("vswayslions"), volatility: "Very High" },
  { name: "5 Lions Dance", provider: "Pragmatic Play", image: PP("vs9lions"), volatility: "Medium" },
  { name: "Candy Blitz", provider: "Pragmatic Play", image: PP("vs20candyblitz"), volatility: "High" },
  { name: "Hot Fiesta", provider: "Pragmatic Play", image: PP("vs20hotfiesta"), volatility: "High" },
  { name: "Wisdom of Athena", provider: "Pragmatic Play", image: PP("vs20wisdomofath"), volatility: "High" },
  { name: "John Hunter and the Tomb of the Scarab Queen", provider: "Pragmatic Play", image: PP("vs25johnhunter"), volatility: "High" },
  { name: "Chilli Heat Megaways", provider: "Pragmatic Play", image: PP("vswayschilliheat"), volatility: "High" },
  { name: "Power of Merlin Megaways", provider: "Pragmatic Play", image: PP("vswaysmerlin"), volatility: "Very High" },
  { name: "Rage of the Seas", provider: "Pragmatic Play", image: PP("vs10rageofsea"), volatility: "Very High" },
  { name: "Hot to Burn Extreme", provider: "Pragmatic Play", image: PP("vs20hotburnx"), volatility: "Very High" },
  { name: "Elemental Gems Megaways", provider: "Pragmatic Play", image: PP("vswayselements"), volatility: "High" },
  { name: "Fishin' Reels", provider: "Pragmatic Play", image: PP("vs20fishingrel"), volatility: "High" },
  { name: "Book of Golden Sands", provider: "Pragmatic Play", image: PP("vs20booksand"), volatility: "High" },
  { name: "Ancient Egypt Classic", provider: "Pragmatic Play", image: PP("vs10egyptcls"), volatility: "High" },
  { name: "Fire Strike 2", provider: "Pragmatic Play", image: PP("vs1firestrike2"), volatility: "High" },
  { name: "Lucky Grace and Charm", provider: "Pragmatic Play", image: PP("vs20luckycharm"), volatility: "High" },
  { name: "Cowboy Coins", provider: "Pragmatic Play", image: PP("vs20cowboycoin"), volatility: "High" },
  { name: "Safari King", provider: "Pragmatic Play", image: PP("vs25safari"), volatility: "High" },
  { name: "Wild Depths", provider: "Pragmatic Play", image: PP("vs20wildepths"), volatility: "Very High" },
  { name: "Gold Party", provider: "Pragmatic Play", image: PP("vs5goldparty"), volatility: "Low" },
  { name: "Monkey Madness", provider: "Pragmatic Play", image: PP("vs20monkeymd"), volatility: "High" },
  { name: "Gates of Gatot Kaca", provider: "Pragmatic Play", image: PP("vs20gkgates"), volatility: "High" },
  { name: "Treasure Wild", provider: "Pragmatic Play", image: PP("vs40treasurewild"), volatility: "High" },
  { name: "Lucky New Year Tiger Treasures", provider: "Pragmatic Play", image: PP("vs20tigertreasure"), volatility: "Medium" },
  { name: "Vegas Nights", provider: "Pragmatic Play", image: PP("vs25vegas"), volatility: "High" },
  { name: "Octobeer Fortunes", provider: "Pragmatic Play", image: PP("vs20octobeer"), volatility: "High" },
  { name: "Emerald King", provider: "Pragmatic Play", image: PP("vs20emeraldking"), volatility: "High" },
  { name: "Floating Dragon Hold & Spin Megaways", provider: "Pragmatic Play", image: PP("vswaysfloatdrg"), volatility: "High" },
  { name: "Piggy Bankers", provider: "Pragmatic Play", image: PP("vs20piggy"), volatility: "High" },
  { name: "Aztec Blaze", provider: "Pragmatic Play", image: PP("vs20aztecblaze"), volatility: "Very High" },
  { name: "Candy Rush", provider: "Pragmatic Play", image: PP("vs20candyrush"), volatility: "High" },
  { name: "Candy Corner", provider: "Pragmatic Play", image: PP("vs20candycorner"), volatility: "Medium" },
  { name: "Big Bass Amazon Xtreme", provider: "Pragmatic Play", image: PP("vs10bigbassamazon"), volatility: "High" },
  { name: "Big Bass Floats My Boat", provider: "Pragmatic Play", image: PP("vs10bigbassfloat"), volatility: "High" },
  { name: "Big Bass Christmas – Frozen Lake", provider: "Pragmatic Play", image: PP("vs10frozenbass"), volatility: "Very High" },
  { name: "Big Bass Halloween 3", provider: "Pragmatic Play", image: PP("vs10halloween3"), volatility: "Very High" },
  { name: "Big Bass Football Bonanza", provider: "Pragmatic Play", image: PP("vs10bigbassfootball"), volatility: "Low" },
  { name: "Zeus vs Hades – Gods of War", provider: "Pragmatic Play", image: PP("vs20zeusvhades"), volatility: "Very High" },
  { name: "Gates of Hades", provider: "Pragmatic Play", image: PP("vs20hadesgates"), volatility: "Very High" },
  { name: "Sword of Ares", provider: "Pragmatic Play", image: PP("vs20swordofares"), volatility: "High" },
  { name: "Forge of Olympus", provider: "Pragmatic Play", image: PP("vs20olympforge"), volatility: "High" },
  { name: "Zeus vs Typhon", provider: "Pragmatic Play", image: PP("vs20zeustyphon"), volatility: "Very High" },
  { name: "The Dog House Multihold", provider: "Pragmatic Play", image: PP("vs20dogmultihold"), volatility: "High" },
  { name: "The Dog House Royal Hunt", provider: "Pragmatic Play", image: PP("vs20doghouserh"), volatility: "High" },
  { name: "The Big Dog House", provider: "Pragmatic Play", image: PP("vs20bigdoghouse"), volatility: "Medium" },
  { name: "Wild West Gold Megaways", provider: "Pragmatic Play", image: PP("vswayswildwest"), volatility: "High" },
  { name: "Madame Destiny Megaways", provider: "Pragmatic Play", image: PP("vswaysmadam"), volatility: "High" },
  { name: "Vampy Party", provider: "Pragmatic Play", image: PP("vs20vampyparty"), volatility: "High" },
  { name: "Juicy Fruits Multihold", provider: "Pragmatic Play", image: PP("vs20juicyfrmh"), volatility: "High" },
  { name: "Cleocatra", provider: "Pragmatic Play", image: PP("vs20cleocatra"), volatility: "High" },
  { name: "Muertos Multiplier Megaways", provider: "Pragmatic Play", image: PP("vswaysmuertos"), volatility: "Very High" },
  { name: "Sanatorium Secrets", provider: "Pragmatic Play", image: PP("vs20sanatorium"), volatility: "Medium" },
  { name: "Joker's Revenge", provider: "Pragmatic Play", image: PP("vs20jokerrev"), volatility: "High" },
  { name: "Sweet Rush Bonanza", provider: "Pragmatic Play", image: PP("vs20sweetrushbon"), volatility: "Very High" },
  { name: "Sticky Bees", provider: "Pragmatic Play", image: PP("vs20stickybees"), volatility: "High" },
  { name: "3 Magic Eggs", provider: "Pragmatic Play", image: PP("vs20magiceggs"), volatility: "High" },
  { name: "5 Lions Reborn", provider: "Pragmatic Play", image: PP("vs20lionsreborn"), volatility: "Very High" },
  { name: "Alien Invaders", provider: "Pragmatic Play", image: PP("vs20alieninv"), volatility: "Very High" },
  { name: "Ancient Island Megaways", provider: "Pragmatic Play", image: PP("vswaysancientisland"), volatility: "High" },
  { name: "Anaconda Gold", provider: "Pragmatic Play", image: PP("vs20anacondagold"), volatility: "Very High" },
  { name: "Argonauts", provider: "Pragmatic Play", image: PP("vs20argonauts"), volatility: "Very High" },
  { name: "Aztec Smash", provider: "Pragmatic Play", image: PP("vs20aztecsmash"), volatility: "High" },
  { name: "Bandit Megaways", provider: "Pragmatic Play", image: PP("vswaysbandit"), volatility: "Very High" },
  { name: "Bigger Barn House Bonanza", provider: "Pragmatic Play", image: PP("vs20bigbarnhouse"), volatility: "Very High" },
  { name: "Bigger Bass Splash", provider: "Pragmatic Play", image: PP("vs10biggerbsplash"), volatility: "High" },
  { name: "Big Bass Bonanza 1000", provider: "Pragmatic Play", image: PP("vs10bigbass1000"), volatility: "Very High" },
  { name: "Big Bass Boxing Bonus Round", provider: "Pragmatic Play", image: PP("vs10bigbassboxing"), volatility: "High" },
  { name: "Big Bass Reel Repeat", provider: "Pragmatic Play", image: PP("vs10bigbassreelrep"), volatility: "Very High" },
  { name: "Big Bass Splash 1000", provider: "Pragmatic Play", image: PP("vs10txbigbass1000"), volatility: "Very High" },
  { name: "Big Bass Trophy Catch", provider: "Pragmatic Play", image: PP("vs10bibasstrophy"), volatility: "Very High" },
  { name: "Bingo Mania", provider: "Pragmatic Play", image: PP("vs20bingomania"), volatility: "Very High" },
  { name: "The Blarney Stone – Jackpot Star", provider: "Pragmatic Play", image: PP("vs20blarney"), volatility: "Medium" },
  { name: "Bloody Dawn", provider: "Pragmatic Play", image: PP("vs20bloodydawn"), volatility: "Very High" },
  { name: "Bounty Hunter", provider: "Pragmatic Play", image: PP("vs20bountyhunter"), volatility: "Very High" },
  { name: "Brick House Bonanza", provider: "Pragmatic Play", image: PP("vs20brickhousebon"), volatility: "High" },
  { name: "Cachorro Sortudo", provider: "Pragmatic Play", image: PP("vs20cachorrosort"), volatility: "Low" },
  { name: "Captain Kraken Megaways", provider: "Pragmatic Play", image: PP("vswaysckraken"), volatility: "Very High" },
  { name: "Cash Surge", provider: "Pragmatic Play", image: PP("vs20cashsurge"), volatility: "High" },
  { name: "Chests of Cai Shen 2", provider: "Pragmatic Play", image: PP("vs20caishen2"), volatility: "Very High" },
  { name: "Chilli Heat Spicy Spins", provider: "Pragmatic Play", image: PP("vs25chilliheatss"), volatility: "High" },
  { name: "Club Tropicana – Happy Hour", provider: "Pragmatic Play", image: PP("vs20clubtropicana"), volatility: "Very High" },
  { name: "CULT", provider: "Pragmatic Play", image: PP("vs20cult"), volatility: "Very High" },
  { name: "Cyberheist City", provider: "Pragmatic Play", image: PP("vs20cyberheist"), volatility: "Very High" },
  { name: "Dino Drop", provider: "Pragmatic Play", image: PP("vs20dinodrop"), volatility: "High" },
  { name: "DJ Neko", provider: "Pragmatic Play", image: PP("vs20djneko"), volatility: "Medium" },
  { name: "Dragon Pots Megaways", provider: "Pragmatic Play", image: PP("vswaysdragonpots"), volatility: "Very High" },
  { name: "Dragon Tiger Fortunes", provider: "Pragmatic Play", image: PP("vs20dragontiger"), volatility: "Very High" },
  { name: "Dragon's Gate – Bonus Choice", provider: "Pragmatic Play", image: PP("vs20dragongate"), volatility: "Medium" },
  { name: "Duel of Night & Day", provider: "Pragmatic Play", image: PP("vs20duelnightday"), volatility: "High" },
  { name: "Emerald King – Wheel of Wealth", provider: "Pragmatic Play", image: PP("vs20emeraldkingwow"), volatility: "Very High" },
  { name: "Emotiwins", provider: "Pragmatic Play", image: PP("vs20emotiwins"), volatility: "Medium" },
  { name: "Escape the Pyramid – Fire & Ice", provider: "Pragmatic Play", image: PP("vs20escapepyramid"), volatility: "High" },
  { name: "Eye of Spartacus", provider: "Pragmatic Play", image: PP("vs20eyespartacus"), volatility: "Very High" },
  { name: "Fiesta Fortune", provider: "Pragmatic Play", image: PP("vs20fiestafortune"), volatility: "High" },
  { name: "Finger Lick'n Free Spins", provider: "Pragmatic Play", image: PP("vs20fingerlickn"), volatility: "High" },
  { name: "Fire Stampede 2", provider: "Pragmatic Play", image: PP("vs20firestampede2"), volatility: "Very High" },
  { name: "Fire Stampede Ultimate", provider: "Pragmatic Play", image: PP("vs20firestampedeult"), volatility: "Very High" },
  { name: "Floating Dragon – Year of the Snake", provider: "Pragmatic Play", image: PP("vs20floatdrgsnake"), volatility: "High" },
  { name: "Floating Dragon Wild Horses", provider: "Pragmatic Play", image: PP("vs20floatdrgwh"), volatility: "Very High" },
  { name: "Fonzo's Feline Fortunes", provider: "Pragmatic Play", image: PP("vs20fonzofeline"), volatility: "High" },
  { name: "Fortune of Aztec", provider: "Pragmatic Play", image: PP("vs20fortuneaztec"), volatility: "High" },
  { name: "Fortune of Olympus", provider: "Pragmatic Play", image: PP("vs20fortuneolympus"), volatility: "Very High" },
  { name: "Frightening Frankie", provider: "Pragmatic Play", image: PP("vs20frightfrankie"), volatility: "Very High" },
  { name: "Gem Fire Fortune", provider: "Pragmatic Play", image: PP("vs20gemfire"), volatility: "Medium" },
  { name: "Gem Trio", provider: "Pragmatic Play", image: PP("vs20gemtrio"), volatility: "Very High" },
  { name: "Genie's Gem Bonanza", provider: "Pragmatic Play", image: PP("vs20geniesgem"), volatility: "Very High" },
  { name: "Gold Party 2 – After Hours", provider: "Pragmatic Play", image: PP("vs5goldparty2"), volatility: "High" },
  { name: "Great Ghosts!", provider: "Pragmatic Play", image: PP("vs20greatghosts"), volatility: "Very High" },
  { name: "Hammerstorm", provider: "Pragmatic Play", image: PP("vs20hammerstorm"), volatility: "Very High" },
  { name: "Happy Dragon", provider: "Pragmatic Play", image: PP("vs20happydragon"), volatility: "High" },
  { name: "Happy Nets", provider: "Pragmatic Play", image: PP("vs20happynets"), volatility: "High" },
  { name: "Haunted Crypt", provider: "Pragmatic Play", image: PP("vs20hauntedcrypt"), volatility: "Very High" },
  { name: "Heartbreakers", provider: "Pragmatic Play", image: PP("vs20heartbreakers"), volatility: "Low" },
  { name: "Hot Tuna", provider: "Pragmatic Play", image: PP("vs20hottuna"), volatility: "High" },
  { name: "Hundreds and Thousands", provider: "Pragmatic Play", image: PP("vs20hundredsthousands"), volatility: "High" },
  { name: "Ice Mints", provider: "Pragmatic Play", image: PP("vs20icemints"), volatility: "Very High" },
  { name: "Idol Pop Fever", provider: "Pragmatic Play", image: PP("vs20idolpopfever"), volatility: "Very High" },
  { name: "Inca Queen", provider: "Pragmatic Play", image: PP("vs20incaqueen"), volatility: "Very High" },
  { name: "Irish Crown", provider: "Pragmatic Play", image: PP("vs20irishcrown"), volatility: "Medium" },
  { name: "Jackpot Blaze", provider: "Pragmatic Play", image: PP("vs20jackpotblaze"), volatility: "Very High" },
  { name: "Jelly Candy", provider: "Pragmatic Play", image: PP("vs20jellycandy"), volatility: "Low" },
  { name: "Jelly Express", provider: "Pragmatic Play", image: PP("vs20jellyexpress"), volatility: "High" },
  { name: "Joker's Jewels Cash", provider: "Pragmatic Play", image: PP("vs5jokercash"), volatility: "High" },
  { name: "Joker's Jewels Hold & Spin", provider: "Pragmatic Play", image: PP("vs5jokerhs"), volatility: "Very High" },
  { name: "Jumbo Safari", provider: "Pragmatic Play", image: PP("vs20jumbosafari"), volatility: "Very High" },
  { name: "Knights vs Barbarians", provider: "Pragmatic Play", image: PP("vs20knightsvs"), volatility: "Very High" },
  { name: "Lava Balls", provider: "Pragmatic Play", image: PP("vs20lavaballs"), volatility: "Very High" },
  { name: "Lobster House", provider: "Pragmatic Play", image: PP("vs20lobsterhouse"), volatility: "Very High" },
  { name: "Lucky Dice", provider: "Pragmatic Play", image: PP("vs20luckydice"), volatility: "Medium" },
  { name: "Lucky Fortune Tree", provider: "Pragmatic Play", image: PP("vs20luckyfortune"), volatility: "Medium" },
  { name: "Lucky Monkey", provider: "Pragmatic Play", image: PP("vs20luckymonkey"), volatility: "Medium" },
  { name: "Lucky Ox", provider: "Pragmatic Play", image: PP("vs20luckyox"), volatility: "Low" },
  { name: "Lucky Panda", provider: "Pragmatic Play", image: PP("vs20luckypanda"), volatility: "Medium" },
  { name: "Lucky Phoenix", provider: "Pragmatic Play", image: PP("vs20luckyphoenix"), volatility: "High" },
  { name: "Lucky Tiger 1000", provider: "Pragmatic Play", image: PP("vs20luckytiger1000"), volatility: "Medium" },
  { name: "Lucky Tiger Gold", provider: "Pragmatic Play", image: PP("vs20luckytigergold"), volatility: "Very High" },
  { name: "Lucky's Wild Pub", provider: "Pragmatic Play", image: PP("vs20luckyspub"), volatility: "High" },
  { name: "Mahjong Wins Super Scatter", provider: "Pragmatic Play", image: PP("vs20mahjongss"), volatility: "High" },
  { name: "Majestic Express – Gold Run", provider: "Pragmatic Play", image: PP("vs20majesticexp"), volatility: "High" },
  { name: "Master Gems", provider: "Pragmatic Play", image: PP("vs5mastergems"), volatility: "Medium" },
  { name: "Mermaid's Treasure Trove", provider: "Pragmatic Play", image: PP("vs20mermaidtrove"), volatility: "Very High" },
  { name: "Money Stacks Megaways", provider: "Pragmatic Play", image: PP("vswaysmoneystacks"), volatility: "High" },
  { name: "Mr Null's Wicked Wares", provider: "Pragmatic Play", image: PP("vs20mrnull"), volatility: "Very High" },
  { name: "Mummy's Jewels 100", provider: "Pragmatic Play", image: PP("vs20mummyjewels"), volatility: "Very High" },
  { name: "Mystic Wishes", provider: "Pragmatic Play", image: PP("vs20mysticwishes"), volatility: "Low" },
  { name: "Olympus Wins", provider: "Pragmatic Play", image: PP("vs20olympuswins"), volatility: "High" },
  { name: "Oracle of Gold", provider: "Pragmatic Play", image: PP("vs20oraclegold"), volatility: "Very High" },
  { name: "Pandemic Rising", provider: "Pragmatic Play", image: PP("vs20pandemic"), volatility: "Very High" },
  { name: "Pig Farm", provider: "Pragmatic Play", image: PP("vs20pigfarm"), volatility: "Low" },
  { name: "Plinko+", provider: "Pragmatic Play", image: PP("vs20plinko"), volatility: "Low" },
  { name: "Raging Waterfall Megaways", provider: "Pragmatic Play", image: PP("vswaysragingwf"), volatility: "High" },
  { name: "Resurrecting Riches", provider: "Pragmatic Play", image: PP("vs20resurrectriches"), volatility: "High" },
  { name: "Ride The Lightning", provider: "Pragmatic Play", image: PP("vs20ridelightning"), volatility: "High" },
  { name: "Rolling in Treasures", provider: "Pragmatic Play", image: PP("vs20rollingtreasures"), volatility: "Very High" },
  { name: "Santa's Slay", provider: "Pragmatic Play", image: PP("vs20santaslay"), volatility: "Very High" },
  { name: "Savannah Legend", provider: "Pragmatic Play", image: PP("vs20savannahlegend"), volatility: "High" },
  { name: "Sleeping Dragon", provider: "Pragmatic Play", image: PP("vs20sleepingdragon"), volatility: "Very High" },
  { name: "Snow Party", provider: "Pragmatic Play", image: PP("vs20snowparty"), volatility: "High" },
  { name: "Spell Master", provider: "Pragmatic Play", image: PP("vs20spellmaster"), volatility: "Very High" },
  { name: "Starlight Princess Super Scatter", provider: "Pragmatic Play", image: PP("vs20starlightss"), volatility: "Very High" },
  { name: "Starlight Wins", provider: "Pragmatic Play", image: PP("vs20starlightwins"), volatility: "Very High" },
  { name: "Steamin' Reels", provider: "Pragmatic Play", image: PP("vs20steaminreels"), volatility: "Very High" },
  { name: "Sugar Rush Super Scatter", provider: "Pragmatic Play", image: PP("vs20sugarrushss"), volatility: "Very High" },
  { name: "Super Gummy Strike", provider: "Pragmatic Play", image: PP("vs20supergummy"), volatility: "Very High" },
  { name: "Super Tiki Strike", provider: "Pragmatic Play", image: PP("vs20supertiki"), volatility: "Very High" },
  { name: "Sweet Bonanza 2500", provider: "Pragmatic Play", image: PP("vs20sugarhits2500"), volatility: "Very High" },
  { name: "Sweet Bonanza Super Scatter", provider: "Pragmatic Play", image: PP("vs20sugarhitsss"), volatility: "High" },
  { name: "Sweet Burst", provider: "Pragmatic Play", image: PP("vs20sweetburst"), volatility: "High" },
  { name: "Sweet Craze", provider: "Pragmatic Play", image: PP("vs20sweetcraze"), volatility: "High" },
  { name: "Treasures of Osiris", provider: "Pragmatic Play", image: PP("vs20treasureosiris"), volatility: "Very High" },
  { name: "Triple Pot Diamond", provider: "Pragmatic Play", image: PP("vs20triplepdiamond"), volatility: "Very High" },
  { name: "Triple Pot Gold", provider: "Pragmatic Play", image: PP("vs20triplepotgold"), volatility: "High" },
  { name: "Triple Pot Plinko – Hercules", provider: "Pragmatic Play", image: PP("vs20tripleplinko"), volatility: "Low" },
  { name: "Tut's Treasure Tower", provider: "Pragmatic Play", image: PP("vs20tutstower"), volatility: "High" },
  { name: "Waves of Poseidon", provider: "Pragmatic Play", image: PP("vs20wavesposeidon"), volatility: "High" },
  { name: "Wheel of Happiness", provider: "Pragmatic Play", image: PP("vs20wheelofhap"), volatility: "High" },
  { name: "Wild West Gold Blazing Bounty", provider: "Pragmatic Play", image: PP("vs40wildwestbb"), volatility: "High" },
  { name: "Wild Wild Riches Returns", provider: "Pragmatic Play", image: PP("vs20wildriches2"), volatility: "Medium" },
  { name: "Wild Wildebeest Wins", provider: "Pragmatic Play", image: PP("vs20wildwildebeest"), volatility: "High" },
  { name: "Wisdom of Athena 1000 Xmas", provider: "Pragmatic Play", image: PP("vs20wisdomxmas"), volatility: "Very High" },
  { name: "Witch Heart Megaways", provider: "Pragmatic Play", image: PP("vswayswitchheart"), volatility: "Very High" },
  { name: "Wolf Gold 4 Pack", provider: "Pragmatic Play", image: PP("vs25wolfgold4"), volatility: "Very High" },
  { name: "You Can Piggy Bank On It", provider: "Pragmatic Play", image: PP("vs20piggybankoni"), volatility: "Very High" },
  { name: "Zombie School Megaways", provider: "Pragmatic Play", image: PP("vswayswzombieschool"), volatility: "High" },
  { name: "Zeus vs Hades – Gods of War 250", provider: "Pragmatic Play", image: PP("vs20zeusvhades250"), volatility: "Very High" },
  // ─── Big Bass extended series ──────────────────────────────────────────────
  { name: "Big Bass Halloween", provider: "Pragmatic Play", image: PP("vs10halloween"), volatility: "High" },
  { name: "Big Bass Vegas Double Down Deluxe", provider: "Pragmatic Play", image: PP("vs10bigbassvdd"), volatility: "High" },
  { name: "Big Bass Return to El Dorado", provider: "Pragmatic Play", image: PP("vs10bigbasseldorado"), volatility: "High" },
  // ─── Dog House extended series ─────────────────────────────────────────────
  { name: "The Dog House 1000", provider: "Pragmatic Play", image: PP("vs20doghouse1000"), volatility: "High" },
  { name: "Doggo-topia", provider: "Pragmatic Play", image: PP("vs20doggotopia"), volatility: "High" },
  // ─── Sweet Bonanza / Sugar / Candy extended ────────────────────────────────
  { name: "Sweet Bonanza Xmas", provider: "Pragmatic Play", image: PP("vs20sugarhitsxmas"), volatility: "High" },
  { name: "Candy Blitz Bombs", provider: "Pragmatic Play", image: PP("vs20candyblitzbombs"), volatility: "High" },
  { name: "Sugar Rush Xmas", provider: "Pragmatic Play", image: PP("vs20sugarrushxmas"), volatility: "High" },
  { name: "Sugar Supreme Powernudge", provider: "Pragmatic Play", image: PP("vs20sugarsupreme"), volatility: "High" },
  { name: "Candy Stars", provider: "Pragmatic Play", image: PP("vs20candystars"), volatility: "High" },
  // ─── Starlight Princess extended ───────────────────────────────────────────
  { name: "Starlight Princess Pachi", provider: "Pragmatic Play", image: PP("vs20starlightpachi"), volatility: "High" },
  // ─── Gates of Olympus extended ─────────────────────────────────────────────
  { name: "Gates of Olympus Megaways", provider: "Pragmatic Play", image: PP("vswaysolympgate"), volatility: "High" },
  { name: "Gates of Olympus Super Scatter", provider: "Pragmatic Play", image: PP("vs20olympgatess"), volatility: "High" },
  // ─── Gold series ───────────────────────────────────────────────────────────
  { name: "Black Bull", provider: "Pragmatic Play", image: PP("vs20blackbull"), volatility: "High" },
  { name: "Gold Rush", provider: "Pragmatic Play", image: PP("vs20goldrush"), volatility: "Medium" },
  { name: "888 Gold", provider: "Pragmatic Play", image: PP("vs10888gold"), volatility: "Low" },
  { name: "Gold Train", provider: "Pragmatic Play", image: PP("vs20goldtrain"), volatility: "High" },
  // ─── Megaways additions ────────────────────────────────────────────────────
  { name: "Jurassic Giants", provider: "Pragmatic Play", image: PP("vswaysjurassic"), volatility: "High" },
  { name: "Aztec Gems Megaways", provider: "Pragmatic Play", image: PP("vswaysaztec"), volatility: "Medium" },
  { name: "Pirate Gold Megaways", provider: "Pragmatic Play", image: PP("vswayspirate"), volatility: "High" },
  { name: "Pyramid King Megaways", provider: "Pragmatic Play", image: PP("vswayspyramid"), volatility: "High" },
  // ─── Full PP catalogue additions ───────────────────────────────────────────
  { name: "3 Genie Wishes", provider: "Pragmatic Play", image: PP("vs20genies"), volatility: "Medium" },
  { name: "5 Lucky Lions", provider: "Pragmatic Play", image: PP("vs9luckylions"), volatility: "Medium" },
  { name: "7 Monkeys", provider: "Pragmatic Play", image: PP("vs7monkeys"), volatility: "Medium" },
  { name: "Ancient Egypt", provider: "Pragmatic Play", image: PP("vs10egypt"), volatility: "Medium" },
  { name: "Bomb Bonanza", provider: "Pragmatic Play", image: PP("vs20bombbonanza"), volatility: "High" },
  { name: "Bounty Gold", provider: "Pragmatic Play", image: PP("vs20bountygold"), volatility: "High" },
  { name: "Buffalo King", provider: "Pragmatic Play", image: PP("vs4bufking"), volatility: "High" },
  { name: "Cash Bonanza", provider: "Pragmatic Play", image: PP("vs20cashbonanza"), volatility: "High" },
  { name: "Coconut Lady", provider: "Pragmatic Play", image: PP("vs20coconutlady"), volatility: "High" },
  { name: "Congo Cash", provider: "Pragmatic Play", image: PP("vs20congocash"), volatility: "High" },
  { name: "Cowboys Gold", provider: "Pragmatic Play", image: PP("vs20cowboysgold"), volatility: "High" },
  { name: "Empire of Riches", provider: "Pragmatic Play", image: PP("vs20empireofriches"), volatility: "High" },
  { name: "Empty the Bank", provider: "Pragmatic Play", image: PP("vs20emptybank"), volatility: "Very High" },
  { name: "Fruity Treats", provider: "Pragmatic Play", image: PP("vs20fruitytreats"), volatility: "High" },
  { name: "Great Rhino", provider: "Pragmatic Play", image: PP("vs20rhino"), volatility: "High" },
  { name: "Great Rhino Deluxe", provider: "Pragmatic Play", image: PP("vs25rhino"), volatility: "High" },
  { name: "Greedy Wolf", provider: "Pragmatic Play", image: PP("vs20greedywolf"), volatility: "High" },
  { name: "Hot Pepper", provider: "Pragmatic Play", image: PP("vs20hotpepper"), volatility: "High" },
  { name: "Hot Safari", provider: "Pragmatic Play", image: PP("vs20hotsafari"), volatility: "Medium" },
  { name: "Hot to Burn Hold & Spin", provider: "Pragmatic Play", image: PP("vs20hotburnhs"), volatility: "High" },
  { name: "Joker King", provider: "Pragmatic Play", image: PP("vs5jokerking"), volatility: "Low" },
  { name: "Journey to the West", provider: "Pragmatic Play", image: PP("vs20jtw"), volatility: "High" },
  { name: "Jungle Gorilla", provider: "Pragmatic Play", image: PP("vs20jungle"), volatility: "High" },
  { name: "Koi Pond", provider: "Pragmatic Play", image: PP("vs20koipond"), volatility: "Medium" },
  { name: "Lady Godiva", provider: "Pragmatic Play", image: PP("vs40ladygodiva"), volatility: "High" },
  { name: "Leprechaun Carol", provider: "Pragmatic Play", image: PP("vs20leprechauncr"), volatility: "High" },
  { name: "Lucky Dragon Ball", provider: "Pragmatic Play", image: PP("vs25dragonball"), volatility: "High" },
  { name: "Lucky New Year", provider: "Pragmatic Play", image: PP("vs25luckynew"), volatility: "Medium" },
  { name: "Madame Destiny", provider: "Pragmatic Play", image: PP("vs20madamedestiny"), volatility: "High" },
  { name: "Magician's Secrets", provider: "Pragmatic Play", image: PP("vs20magiciansecret"), volatility: "High" },
  { name: "Mammoth Gold Megaways", provider: "Pragmatic Play", image: PP("vswaysmammoth"), volatility: "High" },
  { name: "Master Joker", provider: "Pragmatic Play", image: PP("vs5masterjoker"), volatility: "Low" },
  { name: "Might of Ra", provider: "Pragmatic Play", image: PP("vs20mightyra"), volatility: "High" },
  { name: "Monster Superlanche", provider: "Pragmatic Play", image: PP("vs50monsterlanche"), volatility: "High" },
  { name: "Moose Mafia", provider: "Pragmatic Play", image: PP("vs40moosemafia"), volatility: "High" },
  { name: "Night of the Living Tales", provider: "Pragmatic Play", image: PP("vs25nighttales"), volatility: "High" },
  { name: "Panther Queen", provider: "Pragmatic Play", image: PP("vs40pantherqueen"), volatility: "High" },
  { name: "Pirate Gold", provider: "Pragmatic Play", image: PP("vs25pirate"), volatility: "High" },
  { name: "Prosperity Fortune Tree", provider: "Pragmatic Play", image: PP("vs20prospertree"), volatility: "High" },
  { name: "Release the Kraken 2", provider: "Pragmatic Play", image: PP("vs20kraken2"), volatility: "High" },
  { name: "Romeo and Juliet", provider: "Pragmatic Play", image: PP("vs20roandju"), volatility: "Medium" },
  { name: "Santa's Wonderland", provider: "Pragmatic Play", image: PP("vs20santawonder"), volatility: "High" },
  { name: "Smugglers Cove", provider: "Pragmatic Play", image: PP("vs20smugglerscove"), volatility: "High" },
  { name: "Spaceman", provider: "Pragmatic Play", image: PP("vs200spaceman"), volatility: "Medium" },
  { name: "Spirit of Adventure", provider: "Pragmatic Play", image: PP("vs20spiritadv"), volatility: "High" },
  { name: "The Catfather", provider: "Pragmatic Play", image: PP("vs20catfather"), volatility: "Medium" },
  { name: "The Catfather Part II", provider: "Pragmatic Play", image: PP("vs20catfatherpt2"), volatility: "Medium" },
  { name: "The Great Chicken Escape", provider: "Pragmatic Play", image: PP("vs20chickenescape"), volatility: "High" },
  { name: "Tree of Riches", provider: "Pragmatic Play", image: PP("vs20treeofriches"), volatility: "High" },
  { name: "Tropical Tiki", provider: "Pragmatic Play", image: PP("vs20tropicaltiki"), volatility: "High" },
  { name: "Voodoo Magic", provider: "Pragmatic Play", image: PP("vs20voodoomagic"), volatility: "High" },
  { name: "Waterfall Wilds", provider: "Pragmatic Play", image: PP("vs20waterfallwilds"), volatility: "High" },
  { name: "Wild Booster", provider: "Pragmatic Play", image: PP("vs20wildbooster"), volatility: "High" },
  { name: "Wild West Duels", provider: "Pragmatic Play", image: PP("vs20wwduels"), volatility: "High" },

  { name: "6 Jokers", provider: "Pragmatic Play", image: PP("vs6jokers"), volatility: "High" },
  { name: "7 Clovers of Fortune", provider: "Pragmatic Play", image: PP("vs7clovers"), volatility: "High" },
  { name: "Angel vs Sinner", provider: "Pragmatic Play", image: PP("vs20angelvssinner"), volatility: "High" },
  { name: "Aztec Treasure Hunt", provider: "Pragmatic Play", image: PP("vs20aztectreasure"), volatility: "High" },
  { name: "Big Bass Bonanza 3 Reeler", provider: "Pragmatic Play", image: PP("vs10bigbass3reel"), volatility: "High" },
  { name: "Big Bass Halloween 2", provider: "Pragmatic Play", image: PP("vs10halloween2"), volatility: "High" },
  { name: "Big Bass Xmas Xtreme", provider: "Pragmatic Play", image: PP("vs10bigbassxmasxt"), volatility: "High" },
  { name: "Bow of Artemis", provider: "Pragmatic Play", image: PP("vs20bowartemis"), volatility: "High" },
  { name: "Buffalo King Untamed Megaways", provider: "Pragmatic Play", image: PP("vswaysbufkingunmd"), volatility: "High" },
  { name: "Chests of Cai Shen", provider: "Pragmatic Play", image: PP("vs20caishen"), volatility: "High" },
  { name: "Crank It Up", provider: "Pragmatic Play", image: PP("vs20crankitup"), volatility: "High" },
  { name: "Dragon Gold 88", provider: "Pragmatic Play", image: PP("vs88dragongold"), volatility: "High" },
  { name: "Dragon King Hot Pots", provider: "Pragmatic Play", image: PP("vs20dragonkingpots"), volatility: "High" },
  { name: "Eternal Empress – Freeze Time", provider: "Pragmatic Play", image: PP("vs20eternalempress"), volatility: "High" },
  { name: "Fangtastic Freespins", provider: "Pragmatic Play", image: PP("vs20fangtastic"), volatility: "High" },
  { name: "Gates of Olympus Xmas 1000", provider: "Pragmatic Play", image: PP("vs20olympxmas1000"), volatility: "High" },
  { name: "Gem Elevator", provider: "Pragmatic Play", image: PP("vs20gemelevator"), volatility: "High" },
  { name: "Hand of Midas 2", provider: "Pragmatic Play", image: PP("vs20midas2"), volatility: "High" },
  { name: "Himalayan Wild", provider: "Pragmatic Play", image: PP("vs20himalayanwild"), volatility: "High" },
  { name: "Hot to Burn – 7 Deadly Free Spins", provider: "Pragmatic Play", image: PP("vs20hotburn7deadly"), volatility: "High" },
  { name: "Hot to Burn Multiplier", provider: "Pragmatic Play", image: PP("vs20hotburnmult"), volatility: "High" },
  { name: "Irish Cash Chips", provider: "Pragmatic Play", image: PP("vs20irishcashchips"), volatility: "High" },
  { name: "Jackpot Hunter", provider: "Pragmatic Play", image: PP("vs20jackpothunter"), volatility: "High" },
  { name: "Joker's Jewels Wild", provider: "Pragmatic Play", image: PP("vs5jokerwild"), volatility: "Low" },
  { name: "Might of Freya Megaways", provider: "Pragmatic Play", image: PP("vswaysfreyamight"), volatility: "High" },
  { name: "Mining Rush", provider: "Pragmatic Play", image: PP("vs20miningrush"), volatility: "High" },
  { name: "Moleionaire", provider: "Pragmatic Play", image: PP("vs20moleionaire"), volatility: "High" },
  { name: "Money Stacks", provider: "Pragmatic Play", image: PP("vs20moneystacks"), volatility: "High" },
  { name: "Mummy's Jewels", provider: "Pragmatic Play", image: PP("vs20mummysjewels"), volatility: "High" },
  { name: "Mustang Gold Megaways", provider: "Pragmatic Play", image: PP("vswaysmustang"), volatility: "High" },
  { name: "Mystery Mice", provider: "Pragmatic Play", image: PP("vs20mysterymice"), volatility: "High" },
  { name: "Penguins Christmas Party Time", provider: "Pragmatic Play", image: PP("vs20penguinschristmas"), volatility: "High" },
  { name: "Release the Kraken Megaways", provider: "Pragmatic Play", image: PP("vswayskraken"), volatility: "High" },
  { name: "Revenge of Loki Megaways", provider: "Pragmatic Play", image: PP("vswayslokirevenge"), volatility: "High" },
  { name: "Running Sushi", provider: "Pragmatic Play", image: PP("vs20runningsushi"), volatility: "Medium" },
  { name: "Samurai Code", provider: "Pragmatic Play", image: PP("vs20samuraicode"), volatility: "High" },
  { name: "Santa's Xmas Rush", provider: "Pragmatic Play", image: PP("vs20santasxmasrush"), volatility: "High" },
  { name: "Sumo Supreme Megaways", provider: "Pragmatic Play", image: PP("vswayssumosupr"), volatility: "High" },
  { name: "Sweet Kingdom", provider: "Pragmatic Play", image: PP("vs20sweetkingdom"), volatility: "High" },
  { name: "The Dog House Muttley Crew", provider: "Pragmatic Play", image: PP("vs20dogmuttleycrew"), volatility: "High" },
  { name: "Tiny Toads", provider: "Pragmatic Play", image: PP("vs20tinytoads"), volatility: "High" },
  { name: "Wolf Gold Ultimate", provider: "Pragmatic Play", image: PP("vs25wolfgoldult"), volatility: "Medium" },
  { name: "Yeti Quest", provider: "Pragmatic Play", image: PP("vs20yetiquest"), volatility: "High" },
  { name: "Big Bass Bonanza – Reel Action", provider: "Pragmatic Play", image: PP("vs10bigbassreelact"), volatility: "High" },

  // ─── Push Gaming ─────────────────────────────────────────────────────────
  { name: "Jammin Jars", provider: "Push Gaming", image: "https://cdn.casinoreviews.net/slot-images/jammin-jars.jpg", volatility: "High" },
  { name: "Jammin Jars 2", provider: "Push Gaming", image: "https://cdn.casinoreviews.net/slot-images/jammin-jars-2.jpg", volatility: "High" },
  { name: "Fat Rabbit", provider: "Push Gaming", image: "https://cdn.casinoreviews.net/slot-images/fat-rabbit.jpg", volatility: "High" },
  { name: "Fat Santa", provider: "Push Gaming", image: "https://cdn.casinoreviews.net/slot-images/fat-santa.jpg", volatility: "High" },
  { name: "Razor Shark", provider: "Push Gaming", image: "https://cdn.casinoreviews.net/slot-images/razor-shark.jpg", volatility: "High" },
  { name: "Wild Swarm", provider: "Push Gaming", image: "https://cdn.casinoreviews.net/slot-images/wild-swarm.jpg", volatility: "Medium" },
  { name: "Reactoonz", provider: "Play'n GO", image: "https://cdn.casinoreviews.net/slot-images/reactoonz.jpg", volatility: "High" },
  { name: "Book of Dead", provider: "Play'n GO", image: "https://cdn.casinoreviews.net/slot-images/book-of-dead.jpg", volatility: "High" },

  // ─── Big Time Gaming ─────────────────────────────────────────────────────
  { name: "Bonanza Megaways", provider: "BTG", image: "https://cdn.casinoreviews.net/slot-images/bonanza-megaways.jpg", volatility: "High" },
  { name: "Extra Chilli Megaways", provider: "BTG", image: "https://cdn.casinoreviews.net/slot-images/extra-chilli.jpg", volatility: "High" },
  { name: "White Rabbit Megaways", provider: "BTG", image: "https://cdn.casinoreviews.net/slot-images/white-rabbit.jpg", volatility: "Very High" },
  { name: "Megaways Jack", provider: "BTG", image: "https://cdn.casinoreviews.net/slot-images/megaways-jack.jpg", volatility: "Very High" },

  // ─── Hacksaw Gaming ───────────────────────────────────────────────────────
  { name: "Stick 'Em", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/stick-em.jpg", volatility: "High" },
  { name: "Chaos Crew", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/chaos-crew.jpg", volatility: "High" },
  { name: "Chaos Crew 2", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/chaos-crew-2.jpg", volatility: "Very High" },
  { name: "Wanted Dead or a Wild", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/wanted-dead-or-a-wild.jpg", volatility: "Very High" },
  { name: "Flesh & Blood", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/flesh-and-blood.jpg", volatility: "Very High" },
  { name: "Scream", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/scream.jpg", volatility: "Very High" },
  { name: "Vampire's Charm", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/vampires-charm.jpg", volatility: "High" },
  { name: "Yeti Quest Gigablox", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/yeti-quest-gigablox.jpg", volatility: "High" },
  { name: "RIOT", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/riot.jpg", volatility: "High" },
  { name: "Reel Joke", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/reel-joke.jpg", volatility: "High" },
  { name: "Goblin's Wood", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/goblins-wood.jpg", volatility: "High" },
  { name: "Blazing Void", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/blazing-void.jpg", volatility: "High" },
  { name: "Clover Links", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/clover-links.jpg", volatility: "High" },
  { name: "Squealin' Riches", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/squealin-riches.jpg", volatility: "High" },
  { name: "Bomb Catcher", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/bomb-catcher.jpg", volatility: "High" },
  { name: "Cash Catcher", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/cash-catcher.jpg", volatility: "High" },
  { name: "Midas & Friends", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/midas-and-friends.jpg", volatility: "High" },
  { name: "Sherlock & Moriarty", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/sherlock-and-moriarty.jpg", volatility: "High" },
  { name: "Laser Fruit", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/laser-fruit.jpg", volatility: "High" },
  { name: "Misery Mining", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/misery-mining.jpg", volatility: "Very High" },
  { name: "Death Row", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/death-row.jpg", volatility: "Very High" },
  { name: "3 Cursed Chests: Hold & Win", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/3-cursed-chests-hold-and-win.jpg", volatility: "High" },
  { name: "Red Rascal", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/red-rascal.jpg", volatility: "High" },
  { name: "Sand and Ashes", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/sand-and-ashes.jpg", volatility: "High" },
  { name: "Magic Piggy OG", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/magic-piggy-og.jpg", volatility: "High" },
  { name: "Le Digger", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/le-digger.jpg", volatility: "High" },
  { name: "Circle of Life", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/circle-of-life.jpg", volatility: "High" },
  { name: "Stormborn", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/stormborn.jpg", volatility: "High" },
  { name: "The Luxe", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/the-luxe.jpg", volatility: "High" },
  { name: "Eye of Medusa", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/eye-of-medusa.jpg", volatility: "High" },
  { name: "Aiko and the Wind Spirit", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/aiko-and-the-wind-spirit.jpg", volatility: "High" },
  { name: "Hot Ross", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/hot-ross.jpg", volatility: "High" },
  { name: "Dark Spiral", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/dark-spiral.jpg", volatility: "Very High" },
  { name: "RIP City", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/rip-city.jpg", volatility: "High" },
  { name: "Hand of Anubis", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/hand-of-anubis.jpg", volatility: "High" },
  { name: "The Bowery Boys", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/the-bowery-boys.jpg", volatility: "High" },
  { name: "2 Wild 2 Die", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/2-wild-2-die.jpg", volatility: "High" },
  { name: "SixSixSix", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/sixsixsix.jpg", volatility: "Very High" },
  { name: "Slayers Inc", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/slayers-inc.jpg", volatility: "High" },
  { name: "Le Pharaoh", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/le-pharaoh.jpg", volatility: "High" },
  { name: "Octo Attack", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/octo-attack.jpg", volatility: "High" },
  { name: "Evil Eyes", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/evil-eyes.jpg", volatility: "High" },
  { name: "Donny Dough", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/donny-dough.jpg", volatility: "High" },
  { name: "Dragon's Domain", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/dragons-domain.jpg", volatility: "High" },
  { name: "Tai the Toad", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/tai-the-toad.jpg", volatility: "High" },
  { name: "Twisted Lab", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/twisted-lab.jpg", volatility: "High" },
  { name: "Ze Zeus", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/ze-zeus.jpg", volatility: "High" },
  { name: "Cursed Crypt", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/cursed-crypt.jpg", volatility: "High" },
  { name: "Jelly Slice", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/jelly-slice.jpg", volatility: "Medium" },
  { name: "Keep'em", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/keepem.jpg", volatility: "High" },
  { name: "Divine Drop", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/divine-drop.jpg", volatility: "High" },
  { name: "Orb of Destiny", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/orb-of-destiny.jpg", volatility: "High" },
  { name: "Cash Crew", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/cash-crew.jpg", volatility: "High" },
  { name: "Rusty & Curly", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/rusty-and-curly.jpg", volatility: "High" },
  { name: "Bouncy Bombs", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/bouncy-bombs.jpg", volatility: "High" },
  { name: "Dawn of Kings", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/dawn-of-kings.jpg", volatility: "High" },
  { name: "Fist of Destruction", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/fist-of-destruction.jpg", volatility: "High" },
  { name: "Beam Boys", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/beam-boys.jpg", volatility: "High" },
  { name: "Feel the Beat", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/feel-the-beat.jpg", volatility: "High" },
  { name: "Dark Summoning", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/dark-summoning.jpg", volatility: "High" },
  { name: "Xmas Drop", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/xmas-drop.jpg", volatility: "High" },
  { name: "Immortal Desire", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/immortal-desire.jpg", volatility: "High" },
  { name: "Ultimate Slot of America", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/ultimate-slot-of-america.jpg", volatility: "High" },
  { name: "Power of Ten", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/power-of-ten.jpg", volatility: "High" },
  { name: "Munchy Milo", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/munchy-milo.jpg", volatility: "High" },
  { name: "Epic Bullets and Bounty", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/epic-bullets-and-bounty.jpg", volatility: "High" },
  { name: "Le Bunny", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/le-bunny.jpg", volatility: "High" },
  { name: "Dusk Princess", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/dusk-princess.jpg", volatility: "High" },
  { name: "Eternal Duel", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/eternal-duel.jpg", volatility: "High" },
  { name: "Superstar Sevens", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/superstar-sevens.jpg", volatility: "Medium" },
  { name: "Zeus Ze Zecond", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/zeus-ze-zecond.jpg", volatility: "High" },
  { name: "Le Fisherman", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/le-fisherman.jpg", volatility: "High" },
  { name: "Pray for Six", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/pray-for-six.jpg", volatility: "High" },
  { name: "Deal With Death", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/deal-with-death.jpg", volatility: "High" },
  { name: "Smoking Dragon", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/smoking-dragon.jpg", volatility: "High" },
  { name: "Toshi Ways Club", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/toshi-ways-club.jpg", volatility: "High" },
  { name: "Donny and Danny", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/donny-and-danny.jpg", volatility: "High" },
  { name: "Jaws of Justice", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/jaws-of-justice.jpg", volatility: "High" },
  { name: "Army of Ares", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/army-of-ares.jpg", volatility: "High" },
  { name: "Le Santa", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/le-santa.jpg", volatility: "High" },
  { name: "Spear of Athena", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/spear-of-athena.jpg", volatility: "High" },
  { name: "Steamrunners", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/steamrunners.jpg", volatility: "High" },
  { name: "Le Cowboy", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/le-cowboy.jpg", volatility: "High" },
  { name: "Sun Princess", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/sun-princess.jpg", volatility: "High" },
  { name: "The Count", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/the-count.jpg", volatility: "High" },
  { name: "Bash Bros", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/bash-bros.jpg", volatility: "High" },
  { name: "The Wildwood Curse", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/the-wildwood-curse.jpg", volatility: "High" },
  { name: "Spinman", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/spinman.jpg", volatility: "High" },
  { name: "Pray for Three", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/pray-for-three.jpg", volatility: "High" },
  { name: "Danny Dollar", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/danny-dollar.jpg", volatility: "High" },
  { name: "Rad Maxx", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/rad-maxx.jpg", volatility: "High" },
  { name: "Reign of Rome", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/reign-of-rome.jpg", volatility: "High" },
  { name: "Fighter Pit", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/fighter-pit.jpg", volatility: "High" },
  { name: "Wishbringer", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/wishbringer.jpg", volatility: "High" },
  { name: "Life and Death", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/life-and-death.jpg", volatility: "Very High" },
  { name: "Dorks of the Deep", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/dorks-of-the-deep.jpg", volatility: "High" },
  { name: "Strength of Hercules", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/strength-of-hercules.jpg", volatility: "High" },
  { name: "Hounds of Hell", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/hounds-of-hell.jpg", volatility: "Very High" },
  { name: "FRKN Bananas", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/frkn-bananas.jpg", volatility: "High" },
  { name: "Marlin Masters", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/marlin-masters.jpg", volatility: "High" },
  { name: "Phoenix DuelReels", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/phoenix-duelreels.jpg", volatility: "High" },
  { name: "Le Viking", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/le-viking.jpg", volatility: "High" },
  { name: "Klowns", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/klowns.jpg", volatility: "High" },
  { name: "Fire my Laser", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/fire-my-laser.jpg", volatility: "High" },
  { name: "Donut Division", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/donut-division.jpg", volatility: "High" },
  { name: "Shaolin Master", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/shaolin-master.jpg", volatility: "High" },
  { name: "Snow Slingers", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/snow-slingers.jpg", volatility: "High" },
  { name: "Duel at Dawn", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/duel-at-dawn.jpg", volatility: "High" },
  { name: "Wings of Horus", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/wings-of-horus.jpg", volatility: "High" },
  { name: "Rise of Ymir", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/rise-of-ymir.jpg", volatility: "High" },
  { name: "Get the CHEESE", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/get-the-cheese.jpg", volatility: "High" },
  { name: "Cloud Princess", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/cloud-princess.jpg", volatility: "High" },
  { name: "Born Wild", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/born-wild.jpg", volatility: "High" },
  { name: "Stack 'Em", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/stack-em.jpg", volatility: "High" },
  { name: "Mighty Masks", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/mighty-masks.jpg", volatility: "High" },
  { name: "Mayan Stackways", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/mayan-stackways.jpg", volatility: "High" },
  { name: "Stormforged", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/stormforged.jpg", volatility: "High" },
  { name: "Frank's Farm", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/franks-farm.jpg", volatility: "High" },
  { name: "Pug Life", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/pug-life.jpg", volatility: "High" },
  { name: "Itero", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/itero.jpg", volatility: "High" },
  { name: "Time Spinners", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/time-spinners.jpg", volatility: "High" },
  { name: "Outlaws Inc", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/outlaws-inc.jpg", volatility: "High" },
  { name: "Book of Time", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/book-of-time.jpg", volatility: "High" },
  { name: "Gronk's Gems", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/gronks-gems.jpg", volatility: "High" },
  { name: "Beast Below", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/beast-below.jpg", volatility: "High" },
  { name: "Densho", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/densho.jpg", volatility: "High" },
  { name: "Ronin Stackways", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/ronin-stackways.jpg", volatility: "High" },
  { name: "Drop 'Em", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/drop-em.jpg", volatility: "High" },
  { name: "Vending Machine", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/vending-machine.jpg", volatility: "High" },
  { name: "Benny the Beer", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/benny-the-beer.jpg", volatility: "High" },
  { name: "Eye of the Panda", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/eye-of-the-panda.jpg", volatility: "High" },
  { name: "Double Rainbow", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/double-rainbow.jpg", volatility: "High" },
  { name: "Undead Fortune", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/undead-fortune.jpg", volatility: "High" },
  { name: "Warrior Ways", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/warrior-ways.jpg", volatility: "Very High" },
  { name: "Dynasty of Death", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/dynasty-of-death.jpg", volatility: "Very High" },
  { name: "Fear the Dark", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/fear-the-dark.jpg", volatility: "Very High" },
  { name: "Cursed Seas", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/cursed-seas.jpg", volatility: "Very High" },
  { name: "Temple of Torment", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/temple-of-torment.jpg", volatility: "Very High" },
  { name: "Bloodthirst", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/bloodthirst.jpg", volatility: "Very High" },
  { name: "Magic Piggy", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/magic-piggy.jpg", volatility: "High" },
  { name: "Rotten", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/rotten.jpg", volatility: "Very High" },

  // ─── NetEnt ────────────────────────────────────────────────────────────────
  { name: "Starburst", provider: "NetEnt", image: "https://cdn.casinoreviews.net/slot-images/starburst.jpg", volatility: "Low" },
  { name: "Dead or Alive 2", provider: "NetEnt", image: "https://cdn.casinoreviews.net/slot-images/dead-or-alive-2.jpg", volatility: "Very High" },

  // ─── Nolimit City ─────────────────────────────────────────────────────────
  { name: "Mental", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/mental.jpg", volatility: "Very High" },
  { name: "xWays Hoarder", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/xways-hoarder.jpg", volatility: "Very High" },
  { name: "xWays Hoarder xSplit", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/xways-hoarder-xsplit.jpg", volatility: "Very High" },
  { name: "Fire in the Hole", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/fire-in-the-hole.jpg", volatility: "Very High" },
  { name: "Fire in the Hole 2", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/fire-in-the-hole-2.jpg", volatility: "Very High" },
  { name: "Fire in the Hole xBomb", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/fire-in-the-hole-xbomb.jpg", volatility: "Very High" },
  { name: "San Quentin xWays", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/san-quentin.jpg", volatility: "Very High" },
  { name: "Tombstone", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/tombstone.jpg", volatility: "Very High" },
  { name: "Tombstone RIP", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/tombstone-rip.jpg", volatility: "Very High" },
  { name: "Tombstone No Mercy", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/tombstone-no-mercy.jpg", volatility: "Very High" },
  { name: "Punk Rocker", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/punk-rocker.jpg", volatility: "Very High" },
  { name: "Punk Toilet", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/punk-toilet.jpg", volatility: "Very High" },
  { name: "Deadwood", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/deadwood.jpg", volatility: "Very High" },
  { name: "Serial", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/serial.jpg", volatility: "Very High" },
  { name: "Milky Ways", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/milky-ways.jpg", volatility: "Very High" },
  { name: "The Rave", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/the-rave.jpg", volatility: "Very High" },
  { name: "Folsom Prison", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/folsom-prison.jpg", volatility: "Very High" },
  { name: "Poison Eve", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/poison-eve.jpg", volatility: "High" },
  { name: "Ohcanada", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/ohcanada.jpg", volatility: "High" },
  { name: "Infectious 5 xWays", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/infectious-5-xways.jpg", volatility: "High" },
  { name: "Roadkill", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/roadkill.jpg", volatility: "High" },
  { name: "Thor's Vengeance", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/thors-vengeance.jpg", volatility: "High" },
  { name: "Book of Shadows", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/book-of-shadows.jpg", volatility: "High" },
  { name: "Barbarian Fury", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/barbarian-fury.jpg", volatility: "Very High" },
  { name: "Dungeon Quest", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/dungeon-quest.jpg", volatility: "High" },
  { name: "School Girl Ultra Rush", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/school-girl-ultra-rush.jpg", volatility: "Very High" },
  { name: "True Grit Redemption", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/true-grit-redemption.jpg", volatility: "Very High" },
  { name: "Loot'enKhamun", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/lootenKhamun.jpg", volatility: "High" },
  { name: "Bonus Bunnies", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/bonus-bunnies.jpg", volatility: "High" },
  { name: "Prison Escape", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/prison-escape.jpg", volatility: "Very High" },
  { name: "Nightfall", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/nightfall.jpg", volatility: "Very High" },
  { name: "Dark Vortex", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/dark-vortex.jpg", volatility: "Very High" },
  { name: "Ice Lobster", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/ice-lobster.jpg", volatility: "High" },
  { name: "Karen Maneater", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/karen-maneater.jpg", volatility: "High" },
  { name: "Annihilator", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/annihilator.jpg", volatility: "High" },
  { name: "True Grit Redemption 2", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/true-grit-redemption-2.jpg", volatility: "Very High" },
  { name: "San Quentin Manhunt", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/san-quentin-manhunt.jpg", volatility: "Very High" },
  { name: "Tombstone Begins", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/tombstone-begins.jpg", volatility: "Very High" },
  { name: "Tombstone Slaughter", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/tombstone-slaughter.jpg", volatility: "Very High" },
  { name: "Punk Rocker 2", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/punk-rocker-2.jpg", volatility: "Very High" },
  { name: "Punk Rocker 3", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/punk-rocker-3.jpg", volatility: "Very High" },
  { name: "Catfish Hunters", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/catfish-hunters.jpg", volatility: "Very High" },
  { name: "The Crypt", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/the-crypt.jpg", volatility: "High" },
  { name: "The Crypt 2", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/the-crypt-2.jpg", volatility: "High" },
  { name: "Supersized", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/supersized.jpg", volatility: "High" },
  { name: "Golden Shower", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/golden-shower.jpg", volatility: "High" },
  { name: "Duck Hunters: Happy Hour", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/duck-hunters-happy-hour.jpg", volatility: "High" },
  { name: "Das xBoot", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/das-xboot.jpg", volatility: "Very High" },
  { name: "Das xBoot Zwei!", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/das-xboot-zwei.jpg", volatility: "Very High" },
  { name: "Crazy Ex Girlfriend", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/crazy-ex-girlfriend.jpg", volatility: "High" },
  { name: "Bizarre", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/bizarre.jpg", volatility: "High" },
  { name: "Bangkok Hilton", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/bangkok-hilton.jpg", volatility: "Very High" },
  { name: "Breakout", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/breakout.jpg", volatility: "High" },
  { name: "Dead Men Walking", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/dead-men-walking.jpg", volatility: "High" },
  { name: "Seamen", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/seamen.jpg", volatility: "Very High" },
  { name: "Tsar Wars", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/tsar-wars.jpg", volatility: "High" },
  { name: "Brute Force: Alien Onslaught", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/brute-force-alien-onslaught.jpg", volatility: "High" },
  { name: "Flight Mode", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/flight-mode.jpg", volatility: "High" },
  { name: "Fire in the Hole 3", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/fire-in-the-hole-3.jpg", volatility: "Very High" },
  { name: "Mental 2", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/mental-2.jpg", volatility: "Very High" },
  { name: "San Quentin 2: Death Row", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/san-quentin-2-death-row.jpg", volatility: "Very High" },
  { name: "Home of the Brave", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/home-of-the-brave.jpg", volatility: "High" },
  { name: "Outsourced", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/outsourced.jpg", volatility: "High" },
  { name: "Nine to Five", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/nine-to-five.jpg", volatility: "High" },
  { name: "Land of the Free", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/land-of-the-free.jpg", volatility: "High" },
  { name: "Blood & Shadow", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/blood-and-shadow.jpg", volatility: "Very High" },
  { name: "Blood Diamond", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/blood-diamond.jpg", volatility: "Very High" },
  { name: "True Kult", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/true-kult.jpg", volatility: "Very High" },
  { name: "Bounty Hunters", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/bounty-hunters.jpg", volatility: "High" },
  { name: "The Cage", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/the-cage.jpg", volatility: "High" },
  { name: "Whacker / Space Donkey", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/whacker-space-donkey.jpg", volatility: "High" },
  { name: "Disturbed", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/disturbed.jpg", volatility: "High" },
  { name: "Kiss My Chainsaw", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/kiss-my-chainsaw.jpg", volatility: "Very High" },
  { name: "Benji Killed In Vegas", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/benji-killed-in-vegas.jpg", volatility: "Very High" },
  { name: "Dead Canary", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/dead-canary.jpg", volatility: "Very High" },
  { name: "Pearl Harbor", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/pearl-harbor.jpg", volatility: "High" },
  { name: "The Border", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/the-border.jpg", volatility: "High" },
  { name: "Remember Gulag", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/remember-gulag.jpg", volatility: "Very High" },
  { name: "Misery Mining", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/misery-mining.jpg", volatility: "High" },
  { name: "Legion X", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/legion-x.jpg", volatility: "Very High" },
  { name: "Evil Goblins xBomb", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/evil-goblins-xbomb.jpg", volatility: "Very High" },
  { name: "El Paso Gunfight xNudge", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/el-paso-gunfight-xnudge.jpg", volatility: "Very High" },
  { name: "East Coast vs West Coast", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/east-coast-vs-west-coast.jpg", volatility: "High" },
  { name: "Harlequin Carnival", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/harlequin-carnival.jpg", volatility: "High" },
  { name: "Gaelic Gold", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/gaelic-gold.jpg", volatility: "High" },

  // ─── Relax Gaming ─────────────────────────────────────────────────────────
  { name: "Money Train 2", provider: "Relax Gaming", image: "https://cdn.casinoreviews.net/slot-images/money-train-2.jpg", volatility: "Very High" },
  { name: "Money Train 3", provider: "Relax Gaming", image: "https://cdn.casinoreviews.net/slot-images/money-train-3.jpg", volatility: "Very High" },
  { name: "Snake Arena", provider: "Relax Gaming", image: "https://cdn.casinoreviews.net/slot-images/snake-arena.jpg", volatility: "Medium" },

  // ─── Elk Studios ──────────────────────────────────────────────────────────
  { name: "Wild Toro", provider: "Elk Studios", image: "https://cdn.casinoreviews.net/slot-images/wild-toro.jpg", volatility: "Medium" },

  // ─── 1x2 Gaming ───────────────────────────────────────────────────────────
  { name: "Gems Gone Wild", provider: "1x2 Gaming", image: "https://cdn.casinoreviews.net/slot-images/gems-gone-wild.jpg", volatility: "Medium" },
];

export function searchSlots(query: string): SlotGame[] {
  if (!query.trim()) return SLOT_GAMES;
  const q = query.toLowerCase();
  return SLOT_GAMES.filter(
    (s) =>
      s.name.toLowerCase().includes(q) ||
      s.provider.toLowerCase().includes(q)
  );
}

export function findSlot(name: string): SlotGame | undefined {
  return SLOT_GAMES.find((s) => s.name.toLowerCase() === name.toLowerCase());
}
