export interface SlotGame {
  name: string;
  provider: string;
  image: string; // CDN thumbnail URL
}

// Pragmatic Play CDN base
const PP = (code: string) =>
  `https://pp-slot-cdn.pragmaticplay.net/game-icons/gs2c/square/${code}.png`;

export const SLOT_GAMES: SlotGame[] = [
  // ─── Pragmatic Play ───────────────────────────────────────────────────────
  { name: "Sweet Bonanza", provider: "Pragmatic Play", image: PP("vs20sugarhits") },
  { name: "Gates of Olympus", provider: "Pragmatic Play", image: PP("vs20olympgate") },
  { name: "Big Bass Bonanza", provider: "Pragmatic Play", image: PP("vs10bigbass") },
  { name: "Dog House Megaways", provider: "Pragmatic Play", image: PP("vswaysdogs") },
  { name: "The Dog House", provider: "Pragmatic Play", image: PP("vs20doghouse") },
  { name: "Starlight Princess", provider: "Pragmatic Play", image: PP("vs20starlight") },
  { name: "Wolf Gold", provider: "Pragmatic Play", image: PP("vs25wolfgold") },
  { name: "Wild West Gold", provider: "Pragmatic Play", image: PP("vs40wildwest") },
  { name: "Fruit Party", provider: "Pragmatic Play", image: PP("vs20fruitparty") },
  { name: "Chilli Heat", provider: "Pragmatic Play", image: PP("vs25chilliheat") },
  { name: "Aztec Gems", provider: "Pragmatic Play", image: PP("vs5aztecgems") },
  { name: "Gems Bonanza", provider: "Pragmatic Play", image: PP("vswaysgem") },
  { name: "Release the Kraken", provider: "Pragmatic Play", image: PP("vs20kraken") },
  { name: "Mustang Gold", provider: "Pragmatic Play", image: PP("vs25mustang") },
  { name: "Juicy Fruits", provider: "Pragmatic Play", image: PP("vs20juicyfr") },
  { name: "Floating Dragon", provider: "Pragmatic Play", image: PP("vs20floatdrg") },
  { name: "Hot to Burn", provider: "Pragmatic Play", image: PP("vs20hotburn") },
  { name: "Peking Luck", provider: "Pragmatic Play", image: PP("vs20pekinglu") },
  { name: "5 Lions Gold", provider: "Pragmatic Play", image: PP("vs50lionsgold") },
  { name: "Lucky Lightning", provider: "Pragmatic Play", image: PP("vs20luckyligh") },
  { name: "Money Mouse", provider: "Pragmatic Play", image: PP("vs25moneymouse") },
  { name: "Magic Journey", provider: "Pragmatic Play", image: PP("vs25magicjourn") },
  { name: "Leprechaun Song", provider: "Pragmatic Play", image: PP("vs20leprecoins") },
  { name: "Da Vinci's Treasure", provider: "Pragmatic Play", image: PP("vs25davinci") },
  { name: "3 Kingdoms", provider: "Pragmatic Play", image: PP("vs25kingdoms") },
  { name: "Great Rhino Megaways", provider: "Pragmatic Play", image: PP("vswaysrhino") },
  { name: "Power of Thor Megaways", provider: "Pragmatic Play", image: PP("vswaysftropics") },
  { name: "Jokers Jewels", provider: "Pragmatic Play", image: PP("vs5joker") },
  { name: "Buffalo King Megaways", provider: "Pragmatic Play", image: PP("vswaysbufking") },
  { name: "Pirate Gold Deluxe", provider: "Pragmatic Play", image: PP("vs40pirate") },
  { name: "Book of Fallen", provider: "Pragmatic Play", image: PP("vs10bookoftut") },
  { name: "Barn Festival", provider: "Pragmatic Play", image: PP("vs20barnfest") },
  { name: "Eye of Cleopatra", provider: "Pragmatic Play", image: PP("vs20eyeofcleo") },
  { name: "Fire Strike", provider: "Pragmatic Play", image: PP("vs1firestrike") },
  { name: "Curse of the Werewolf Megaways", provider: "Pragmatic Play", image: PP("vswayswwriches") },
  { name: "Cash Elevator", provider: "Pragmatic Play", image: PP("vs20cashelev") },
  { name: "Christmas Carol Megaways", provider: "Pragmatic Play", image: PP("vswayschristmas") },
  { name: "Drill That Gold", provider: "Pragmatic Play", image: PP("vs20drillgold") },
  { name: "Big Bass Splash", provider: "Pragmatic Play", image: PP("vs10txbigbass") },
  { name: "Rainbow Gold", provider: "Pragmatic Play", image: PP("vs5rainbowgold") },
  { name: "Sweet Bonanza 1000", provider: "Pragmatic Play", image: PP("vs20sugarhits1000") },
  { name: "Gates of Olympus 1000", provider: "Pragmatic Play", image: PP("vs20olympgate1000") },
  { name: "Starlight Princess 1000", provider: "Pragmatic Play", image: PP("vs20starlight1000") },
  { name: "Sugar Rush", provider: "Pragmatic Play", image: PP("vs20sugarrush") },
  { name: "Sugar Rush 1000", provider: "Pragmatic Play", image: PP("vs20sugarrush1000") },
  { name: "Fruit Party 2", provider: "Pragmatic Play", image: PP("vs20fruitparty2") },
  { name: "Bigger Bass Bonanza", provider: "Pragmatic Play", image: PP("vs10bigbass2") },
  { name: "Big Bass Bonanza Megaways", provider: "Pragmatic Play", image: PP("vswaysbigbass") },
  { name: "Big Bass Vegas", provider: "Pragmatic Play", image: PP("vs10bigbassvegas") },
  { name: "Big Bass Hold & Spinner Megaways", provider: "Pragmatic Play", image: PP("vs10bbbonanza3") },
  { name: "Big Bass Day at the Races", provider: "Pragmatic Play", image: PP("vs10bbdayraces") },
  { name: "Big Bass Christmas Bash", provider: "Pragmatic Play", image: PP("vs10christmasbass") },
  { name: "Christmas Big Bass Bonanza", provider: "Pragmatic Play", image: PP("vs20xmasbass") },
  { name: "The Hand of Midas", provider: "Pragmatic Play", image: PP("vs20midas") },
  { name: "Rise of Giza PowerNudge", provider: "Pragmatic Play", image: PP("vs20riseofgiza") },
  { name: "Goblin Heist Powernudge", provider: "Pragmatic Play", image: PP("vs20gobnudge") },
  { name: "5 Lions", provider: "Pragmatic Play", image: PP("vs10lions") },
  { name: "5 Lions Megaways", provider: "Pragmatic Play", image: PP("vswayslions") },
  { name: "5 Lions Dance", provider: "Pragmatic Play", image: PP("vs9lions") },
  { name: "Candy Blitz", provider: "Pragmatic Play", image: PP("vs20candyblitz") },
  { name: "Hot Fiesta", provider: "Pragmatic Play", image: PP("vs20hotfiesta") },
  { name: "Wisdom of Athena", provider: "Pragmatic Play", image: PP("vs20wisdomofath") },
  { name: "John Hunter and the Tomb of the Scarab Queen", provider: "Pragmatic Play", image: PP("vs25johnhunter") },
  { name: "Chilli Heat Megaways", provider: "Pragmatic Play", image: PP("vswayschilliheat") },
  { name: "Power of Merlin Megaways", provider: "Pragmatic Play", image: PP("vswaysmerlin") },
  { name: "Rage of the Seas", provider: "Pragmatic Play", image: PP("vs10rageofsea") },
  { name: "Hot to Burn Extreme", provider: "Pragmatic Play", image: PP("vs20hotburnx") },
  { name: "Elemental Gems Megaways", provider: "Pragmatic Play", image: PP("vswayselements") },
  { name: "Fishin' Reels", provider: "Pragmatic Play", image: PP("vs20fishingrel") },
  { name: "Book of Golden Sands", provider: "Pragmatic Play", image: PP("vs20booksand") },
  { name: "Ancient Egypt Classic", provider: "Pragmatic Play", image: PP("vs10egyptcls") },
  { name: "Fire Strike 2", provider: "Pragmatic Play", image: PP("vs1firestrike2") },
  { name: "Lucky Grace and Charm", provider: "Pragmatic Play", image: PP("vs20luckycharm") },
  { name: "Cowboy Coins", provider: "Pragmatic Play", image: PP("vs20cowboycoin") },
  { name: "Safari King", provider: "Pragmatic Play", image: PP("vs25safari") },
  { name: "Wild Depths", provider: "Pragmatic Play", image: PP("vs20wildepths") },
  { name: "Gold Party", provider: "Pragmatic Play", image: PP("vs5goldparty") },
  { name: "Monkey Madness", provider: "Pragmatic Play", image: PP("vs20monkeymd") },
  { name: "Gates of Gatot Kaca", provider: "Pragmatic Play", image: PP("vs20gkgates") },
  { name: "Treasure Wild", provider: "Pragmatic Play", image: PP("vs40treasurewild") },
  { name: "Lucky New Year Tiger Treasures", provider: "Pragmatic Play", image: PP("vs20tigertreasure") },
  { name: "Vegas Nights", provider: "Pragmatic Play", image: PP("vs25vegas") },
  { name: "Octobeer Fortunes", provider: "Pragmatic Play", image: PP("vs20octobeer") },
  { name: "Emerald King", provider: "Pragmatic Play", image: PP("vs20emeraldking") },
  { name: "Floating Dragon Hold & Spin Megaways", provider: "Pragmatic Play", image: PP("vswaysfloatdrg") },
  { name: "Piggy Bankers", provider: "Pragmatic Play", image: PP("vs20piggy") },
  { name: "Aztec Blaze", provider: "Pragmatic Play", image: PP("vs20aztecblaze") },
  { name: "Candy Rush", provider: "Pragmatic Play", image: PP("vs20candyrush") },
  { name: "Candy Corner", provider: "Pragmatic Play", image: PP("vs20candycorner") },
  { name: "Big Bass Amazon Xtreme", provider: "Pragmatic Play", image: PP("vs10bigbassamazon") },
  { name: "Big Bass Floats My Boat", provider: "Pragmatic Play", image: PP("vs10bigbassfloat") },
  { name: "Big Bass Christmas – Frozen Lake", provider: "Pragmatic Play", image: PP("vs10frozenbass") },
  { name: "Big Bass Halloween 3", provider: "Pragmatic Play", image: PP("vs10halloween3") },
  { name: "Big Bass Football Bonanza", provider: "Pragmatic Play", image: PP("vs10bigbassfootball") },
  { name: "Zeus vs Hades – Gods of War", provider: "Pragmatic Play", image: PP("vs20zeusvhades") },
  { name: "Gates of Hades", provider: "Pragmatic Play", image: PP("vs20hadesgates") },
  { name: "Sword of Ares", provider: "Pragmatic Play", image: PP("vs20swordofares") },
  { name: "Forge of Olympus", provider: "Pragmatic Play", image: PP("vs20olympforge") },
  { name: "Zeus vs Typhon", provider: "Pragmatic Play", image: PP("vs20zeustyphon") },
  { name: "The Dog House Multihold", provider: "Pragmatic Play", image: PP("vs20dogmultihold") },
  { name: "The Dog House Royal Hunt", provider: "Pragmatic Play", image: PP("vs20doghouserh") },
  { name: "The Big Dog House", provider: "Pragmatic Play", image: PP("vs20bigdoghouse") },
  { name: "Wild West Gold Megaways", provider: "Pragmatic Play", image: PP("vswayswildwest") },
  { name: "Madame Destiny Megaways", provider: "Pragmatic Play", image: PP("vswaysmadam") },
  { name: "Vampy Party", provider: "Pragmatic Play", image: PP("vs20vampyparty") },
  { name: "Juicy Fruits Multihold", provider: "Pragmatic Play", image: PP("vs20juicyfrmh") },
  { name: "Cleocatra", provider: "Pragmatic Play", image: PP("vs20cleocatra") },
  { name: "Muertos Multiplier Megaways", provider: "Pragmatic Play", image: PP("vswaysmuertos") },
  { name: "Sanatorium Secrets", provider: "Pragmatic Play", image: PP("vs20sanatorium") },
  { name: "Joker's Revenge", provider: "Pragmatic Play", image: PP("vs20jokerrev") },

  // ─── Push Gaming ─────────────────────────────────────────────────────────
  { name: "Jammin Jars", provider: "Push Gaming", image: "https://cdn.casinoreviews.net/slot-images/jammin-jars.jpg" },
  { name: "Jammin Jars 2", provider: "Push Gaming", image: "https://cdn.casinoreviews.net/slot-images/jammin-jars-2.jpg" },
  { name: "Fat Rabbit", provider: "Push Gaming", image: "https://cdn.casinoreviews.net/slot-images/fat-rabbit.jpg" },
  { name: "Fat Santa", provider: "Push Gaming", image: "https://cdn.casinoreviews.net/slot-images/fat-santa.jpg" },
  { name: "Razor Shark", provider: "Push Gaming", image: "https://cdn.casinoreviews.net/slot-images/razor-shark.jpg" },
  { name: "Wild Swarm", provider: "Push Gaming", image: "https://cdn.casinoreviews.net/slot-images/wild-swarm.jpg" },
  { name: "Reactoonz", provider: "Play'n GO", image: "https://cdn.casinoreviews.net/slot-images/reactoonz.jpg" },
  { name: "Book of Dead", provider: "Play'n GO", image: "https://cdn.casinoreviews.net/slot-images/book-of-dead.jpg" },

  // ─── Big Time Gaming ─────────────────────────────────────────────────────
  { name: "Bonanza Megaways", provider: "BTG", image: "https://cdn.casinoreviews.net/slot-images/bonanza-megaways.jpg" },
  { name: "Extra Chilli Megaways", provider: "BTG", image: "https://cdn.casinoreviews.net/slot-images/extra-chilli.jpg" },
  { name: "White Rabbit Megaways", provider: "BTG", image: "https://cdn.casinoreviews.net/slot-images/white-rabbit.jpg" },
  { name: "Megaways Jack", provider: "BTG", image: "https://cdn.casinoreviews.net/slot-images/megaways-jack.jpg" },

  // ─── Hacksaw Gaming ───────────────────────────────────────────────────────
  { name: "Stick 'Em", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/stick-em.jpg" },
  { name: "Chaos Crew", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/chaos-crew.jpg" },
  { name: "Chaos Crew 2", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/chaos-crew-2.jpg" },
  { name: "Wanted Dead or a Wild", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/wanted-dead-or-a-wild.jpg" },
  { name: "Flesh & Blood", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/flesh-and-blood.jpg" },
  { name: "Scream", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/scream.jpg" },
  { name: "Vampire's Charm", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/vampires-charm.jpg" },
  { name: "Yeti Quest Gigablox", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/yeti-quest-gigablox.jpg" },
  { name: "RIOT", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/riot.jpg" },
  { name: "Reel Joke", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/reel-joke.jpg" },
  { name: "Goblin's Wood", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/goblins-wood.jpg" },
  { name: "Blazing Void", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/blazing-void.jpg" },
  { name: "Clover Links", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/clover-links.jpg" },
  { name: "Squealin' Riches", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/squealin-riches.jpg" },
  { name: "Bomb Catcher", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/bomb-catcher.jpg" },
  { name: "Cash Catcher", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/cash-catcher.jpg" },
  { name: "Midas & Friends", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/midas-and-friends.jpg" },
  { name: "Sherlock & Moriarty", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/sherlock-and-moriarty.jpg" },
  { name: "Laser Fruit", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/laser-fruit.jpg" },
  { name: "Misery Mining", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/misery-mining.jpg" },
  { name: "Death Row", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/death-row.jpg" },
  { name: "3 Cursed Chests: Hold & Win", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/3-cursed-chests-hold-and-win.jpg" },
  { name: "Red Rascal", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/red-rascal.jpg" },
  { name: "Sand and Ashes", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/sand-and-ashes.jpg" },
  { name: "Magic Piggy OG", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/magic-piggy-og.jpg" },
  { name: "Le Digger", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/le-digger.jpg" },
  { name: "Circle of Life", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/circle-of-life.jpg" },
  { name: "Stormborn", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/stormborn.jpg" },
  { name: "The Luxe", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/the-luxe.jpg" },
  { name: "Eye of Medusa", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/eye-of-medusa.jpg" },
  { name: "Aiko and the Wind Spirit", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/aiko-and-the-wind-spirit.jpg" },
  { name: "Hot Ross", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/hot-ross.jpg" },
  { name: "Dark Spiral", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/dark-spiral.jpg" },
  { name: "RIP City", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/rip-city.jpg" },
  { name: "Hand of Anubis", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/hand-of-anubis.jpg" },
  { name: "The Bowery Boys", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/the-bowery-boys.jpg" },
  { name: "2 Wild 2 Die", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/2-wild-2-die.jpg" },
  { name: "SixSixSix", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/sixsixsix.jpg" },
  { name: "Slayers Inc", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/slayers-inc.jpg" },
  { name: "Le Pharaoh", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/le-pharaoh.jpg" },
  { name: "Octo Attack", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/octo-attack.jpg" },
  { name: "Evil Eyes", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/evil-eyes.jpg" },
  { name: "Donny Dough", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/donny-dough.jpg" },
  { name: "Dragon's Domain", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/dragons-domain.jpg" },
  { name: "Tai the Toad", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/tai-the-toad.jpg" },
  { name: "Twisted Lab", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/twisted-lab.jpg" },
  { name: "Ze Zeus", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/ze-zeus.jpg" },
  { name: "Cursed Crypt", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/cursed-crypt.jpg" },
  { name: "Jelly Slice", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/jelly-slice.jpg" },
  { name: "Keep'em", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/keepem.jpg" },
  { name: "Divine Drop", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/divine-drop.jpg" },
  { name: "Orb of Destiny", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/orb-of-destiny.jpg" },
  { name: "Cash Crew", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/cash-crew.jpg" },
  { name: "Rusty & Curly", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/rusty-and-curly.jpg" },
  { name: "Bouncy Bombs", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/bouncy-bombs.jpg" },
  { name: "Dawn of Kings", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/dawn-of-kings.jpg" },
  { name: "Fist of Destruction", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/fist-of-destruction.jpg" },
  { name: "Beam Boys", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/beam-boys.jpg" },
  { name: "Feel the Beat", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/feel-the-beat.jpg" },
  { name: "Dark Summoning", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/dark-summoning.jpg" },
  { name: "Xmas Drop", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/xmas-drop.jpg" },
  { name: "Immortal Desire", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/immortal-desire.jpg" },
  { name: "Ultimate Slot of America", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/ultimate-slot-of-america.jpg" },
  { name: "Power of Ten", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/power-of-ten.jpg" },
  { name: "Munchy Milo", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/munchy-milo.jpg" },
  { name: "Epic Bullets and Bounty", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/epic-bullets-and-bounty.jpg" },
  { name: "Le Bunny", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/le-bunny.jpg" },
  { name: "Dusk Princess", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/dusk-princess.jpg" },
  { name: "Eternal Duel", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/eternal-duel.jpg" },
  { name: "Superstar Sevens", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/superstar-sevens.jpg" },
  { name: "Zeus Ze Zecond", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/zeus-ze-zecond.jpg" },
  { name: "Le Fisherman", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/le-fisherman.jpg" },
  { name: "Pray for Six", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/pray-for-six.jpg" },
  { name: "Deal With Death", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/deal-with-death.jpg" },
  { name: "Smoking Dragon", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/smoking-dragon.jpg" },
  { name: "Toshi Ways Club", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/toshi-ways-club.jpg" },
  { name: "Donny and Danny", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/donny-and-danny.jpg" },
  { name: "Jaws of Justice", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/jaws-of-justice.jpg" },
  { name: "Army of Ares", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/army-of-ares.jpg" },
  { name: "Le Santa", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/le-santa.jpg" },
  { name: "Spear of Athena", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/spear-of-athena.jpg" },
  { name: "Steamrunners", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/steamrunners.jpg" },
  { name: "Le Cowboy", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/le-cowboy.jpg" },
  { name: "Sun Princess", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/sun-princess.jpg" },
  { name: "The Count", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/the-count.jpg" },
  { name: "Bash Bros", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/bash-bros.jpg" },
  { name: "The Wildwood Curse", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/the-wildwood-curse.jpg" },
  { name: "Spinman", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/spinman.jpg" },
  { name: "Pray for Three", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/pray-for-three.jpg" },
  { name: "Danny Dollar", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/danny-dollar.jpg" },
  { name: "Rad Maxx", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/rad-maxx.jpg" },
  { name: "Reign of Rome", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/reign-of-rome.jpg" },
  { name: "Fighter Pit", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/fighter-pit.jpg" },
  { name: "Wishbringer", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/wishbringer.jpg" },
  { name: "Life and Death", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/life-and-death.jpg" },
  { name: "Dorks of the Deep", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/dorks-of-the-deep.jpg" },
  { name: "Strength of Hercules", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/strength-of-hercules.jpg" },
  { name: "Hounds of Hell", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/hounds-of-hell.jpg" },
  { name: "FRKN Bananas", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/frkn-bananas.jpg" },
  { name: "Marlin Masters", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/marlin-masters.jpg" },
  { name: "Phoenix DuelReels", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/phoenix-duelreels.jpg" },
  { name: "Le Viking", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/le-viking.jpg" },
  { name: "Klowns", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/klowns.jpg" },
  { name: "Fire my Laser", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/fire-my-laser.jpg" },
  { name: "Donut Division", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/donut-division.jpg" },
  { name: "Shaolin Master", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/shaolin-master.jpg" },
  { name: "Snow Slingers", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/snow-slingers.jpg" },
  { name: "Duel at Dawn", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/duel-at-dawn.jpg" },
  { name: "Wings of Horus", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/wings-of-horus.jpg" },
  { name: "Rise of Ymir", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/rise-of-ymir.jpg" },
  { name: "Get the CHEESE", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/get-the-cheese.jpg" },
  { name: "Cloud Princess", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/cloud-princess.jpg" },
  { name: "Born Wild", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/born-wild.jpg" },
  { name: "Stack 'Em", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/stack-em.jpg" },
  { name: "Mighty Masks", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/mighty-masks.jpg" },
  { name: "Mayan Stackways", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/mayan-stackways.jpg" },
  { name: "Stormforged", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/stormforged.jpg" },
  { name: "Frank's Farm", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/franks-farm.jpg" },
  { name: "Pug Life", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/pug-life.jpg" },
  { name: "Itero", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/itero.jpg" },
  { name: "Time Spinners", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/time-spinners.jpg" },
  { name: "Outlaws Inc", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/outlaws-inc.jpg" },
  { name: "Book of Time", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/book-of-time.jpg" },
  { name: "Gronk's Gems", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/gronks-gems.jpg" },
  { name: "Beast Below", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/beast-below.jpg" },
  { name: "Densho", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/densho.jpg" },
  { name: "Ronin Stackways", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/ronin-stackways.jpg" },
  { name: "Drop 'Em", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/drop-em.jpg" },
  { name: "Vending Machine", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/vending-machine.jpg" },
  { name: "Benny the Beer", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/benny-the-beer.jpg" },
  { name: "Eye of the Panda", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/eye-of-the-panda.jpg" },
  { name: "Double Rainbow", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/double-rainbow.jpg" },
  { name: "Undead Fortune", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/undead-fortune.jpg" },
  { name: "Warrior Ways", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/warrior-ways.jpg" },
  { name: "Dynasty of Death", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/dynasty-of-death.jpg" },
  { name: "Fear the Dark", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/fear-the-dark.jpg" },
  { name: "Cursed Seas", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/cursed-seas.jpg" },
  { name: "Temple of Torment", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/temple-of-torment.jpg" },
  { name: "Bloodthirst", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/bloodthirst.jpg" },
  { name: "Magic Piggy", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/magic-piggy.jpg" },
  { name: "Rotten", provider: "Hacksaw Gaming", image: "https://cdn.casinoreviews.net/slot-images/rotten.jpg" },

  // ─── NetEnt ────────────────────────────────────────────────────────────────
  { name: "Starburst", provider: "NetEnt", image: "https://cdn.casinoreviews.net/slot-images/starburst.jpg" },
  { name: "Dead or Alive 2", provider: "NetEnt", image: "https://cdn.casinoreviews.net/slot-images/dead-or-alive-2.jpg" },

  // ─── Nolimit City ─────────────────────────────────────────────────────────
  { name: "Mental", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/mental.jpg" },
  { name: "xWays Hoarder", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/xways-hoarder.jpg" },
  { name: "xWays Hoarder xSplit", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/xways-hoarder-xsplit.jpg" },
  { name: "Fire in the Hole", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/fire-in-the-hole.jpg" },
  { name: "Fire in the Hole 2", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/fire-in-the-hole-2.jpg" },
  { name: "Fire in the Hole xBomb", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/fire-in-the-hole-xbomb.jpg" },
  { name: "San Quentin xWays", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/san-quentin.jpg" },
  { name: "Tombstone", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/tombstone.jpg" },
  { name: "Tombstone RIP", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/tombstone-rip.jpg" },
  { name: "Tombstone No Mercy", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/tombstone-no-mercy.jpg" },
  { name: "Punk Rocker", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/punk-rocker.jpg" },
  { name: "Punk Toilet", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/punk-toilet.jpg" },
  { name: "Deadwood", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/deadwood.jpg" },
  { name: "Serial", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/serial.jpg" },
  { name: "Milky Ways", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/milky-ways.jpg" },
  { name: "The Rave", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/the-rave.jpg" },
  { name: "Folsom Prison", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/folsom-prison.jpg" },
  { name: "Poison Eve", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/poison-eve.jpg" },
  { name: "Ohcanada", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/ohcanada.jpg" },
  { name: "Infectious 5 xWays", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/infectious-5-xways.jpg" },
  { name: "Roadkill", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/roadkill.jpg" },
  { name: "Thor's Vengeance", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/thors-vengeance.jpg" },
  { name: "Book of Shadows", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/book-of-shadows.jpg" },
  { name: "Barbarian Fury", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/barbarian-fury.jpg" },
  { name: "Dungeon Quest", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/dungeon-quest.jpg" },
  { name: "School Girl Ultra Rush", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/school-girl-ultra-rush.jpg" },
  { name: "True Grit Redemption", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/true-grit-redemption.jpg" },
  { name: "Loot'enKhamun", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/lootenKhamun.jpg" },
  { name: "Bonus Bunnies", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/bonus-bunnies.jpg" },
  { name: "Prison Escape", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/prison-escape.jpg" },
  { name: "Nightfall", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/nightfall.jpg" },
  { name: "Dark Vortex", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/dark-vortex.jpg" },
  { name: "Ice Lobster", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/ice-lobster.jpg" },
  { name: "Karen Maneater", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/karen-maneater.jpg" },
  { name: "Annihilator", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/annihilator.jpg" },
  { name: "True Grit Redemption 2", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/true-grit-redemption-2.jpg" },
  { name: "San Quentin Manhunt", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/san-quentin-manhunt.jpg" },
  { name: "Tombstone Begins", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/tombstone-begins.jpg" },
  { name: "Tombstone Slaughter", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/tombstone-slaughter.jpg" },
  { name: "Punk Rocker 2", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/punk-rocker-2.jpg" },
  { name: "Punk Rocker 3", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/punk-rocker-3.jpg" },
  { name: "Catfish Hunters", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/catfish-hunters.jpg" },
  { name: "The Crypt", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/the-crypt.jpg" },
  { name: "The Crypt 2", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/the-crypt-2.jpg" },
  { name: "Supersized", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/supersized.jpg" },
  { name: "Golden Shower", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/golden-shower.jpg" },
  { name: "Duck Hunters: Happy Hour", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/duck-hunters-happy-hour.jpg" },
  { name: "Das xBoot", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/das-xboot.jpg" },
  { name: "Das xBoot Zwei!", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/das-xboot-zwei.jpg" },
  { name: "Crazy Ex Girlfriend", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/crazy-ex-girlfriend.jpg" },
  { name: "Bizarre", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/bizarre.jpg" },
  { name: "Bangkok Hilton", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/bangkok-hilton.jpg" },
  { name: "Breakout", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/breakout.jpg" },
  { name: "Dead Men Walking", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/dead-men-walking.jpg" },
  { name: "Seamen", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/seamen.jpg" },
  { name: "Tsar Wars", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/tsar-wars.jpg" },
  { name: "Brute Force: Alien Onslaught", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/brute-force-alien-onslaught.jpg" },
  { name: "Flight Mode", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/flight-mode.jpg" },
  { name: "Fire in the Hole 3", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/fire-in-the-hole-3.jpg" },
  { name: "Mental 2", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/mental-2.jpg" },
  { name: "San Quentin 2: Death Row", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/san-quentin-2-death-row.jpg" },
  { name: "Home of the Brave", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/home-of-the-brave.jpg" },
  { name: "Outsourced", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/outsourced.jpg" },
  { name: "Nine to Five", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/nine-to-five.jpg" },
  { name: "Land of the Free", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/land-of-the-free.jpg" },
  { name: "Blood & Shadow", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/blood-and-shadow.jpg" },
  { name: "Blood Diamond", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/blood-diamond.jpg" },
  { name: "True Kult", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/true-kult.jpg" },
  { name: "Bounty Hunters", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/bounty-hunters.jpg" },
  { name: "The Cage", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/the-cage.jpg" },
  { name: "Whacker / Space Donkey", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/whacker-space-donkey.jpg" },
  { name: "Disturbed", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/disturbed.jpg" },
  { name: "Kiss My Chainsaw", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/kiss-my-chainsaw.jpg" },
  { name: "Benji Killed In Vegas", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/benji-killed-in-vegas.jpg" },
  { name: "Dead Canary", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/dead-canary.jpg" },
  { name: "Pearl Harbor", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/pearl-harbor.jpg" },
  { name: "The Border", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/the-border.jpg" },
  { name: "Remember Gulag", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/remember-gulag.jpg" },
  { name: "Misery Mining", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/misery-mining.jpg" },
  { name: "Legion X", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/legion-x.jpg" },
  { name: "Evil Goblins xBomb", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/evil-goblins-xbomb.jpg" },
  { name: "El Paso Gunfight xNudge", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/el-paso-gunfight-xnudge.jpg" },
  { name: "East Coast vs West Coast", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/east-coast-vs-west-coast.jpg" },
  { name: "Harlequin Carnival", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/harlequin-carnival.jpg" },
  { name: "Gaelic Gold", provider: "Nolimit City", image: "https://cdn.casinoreviews.net/slot-images/gaelic-gold.jpg" },

  // ─── Relax Gaming ─────────────────────────────────────────────────────────
  { name: "Money Train 2", provider: "Relax Gaming", image: "https://cdn.casinoreviews.net/slot-images/money-train-2.jpg" },
  { name: "Money Train 3", provider: "Relax Gaming", image: "https://cdn.casinoreviews.net/slot-images/money-train-3.jpg" },
  { name: "Snake Arena", provider: "Relax Gaming", image: "https://cdn.casinoreviews.net/slot-images/snake-arena.jpg" },

  // ─── Elk Studios ──────────────────────────────────────────────────────────
  { name: "Wild Toro", provider: "Elk Studios", image: "https://cdn.casinoreviews.net/slot-images/wild-toro.jpg" },

  // ─── 1x2 Gaming ───────────────────────────────────────────────────────────
  { name: "Gems Gone Wild", provider: "1x2 Gaming", image: "https://cdn.casinoreviews.net/slot-images/gems-gone-wild.jpg" },
];

export function searchSlots(query: string): SlotGame[] {
  if (!query.trim()) return SLOT_GAMES;
  const q = query.toLowerCase();
  return SLOT_GAMES.filter(
    (s) =>
      s.name.toLowerCase().includes(q) ||
      s.provider.toLowerCase().includes(q)
  );
}

export function findSlot(name: string): SlotGame | undefined {
  return SLOT_GAMES.find((s) => s.name.toLowerCase() === name.toLowerCase());
}
